import re

city_mapping = {
    'Jerusalem' : 'Sarasota',
'Osaka' : 'Huntsville',
'Edo' : 'Seaside',
'Budapest' : 'Torrance',
'Klagenfurt' : 'Saint Petersburg',
'Matsuyama' : 'Santa Barbara',
'Tehran' : 'Pasadena',
'Lisbon' : 'Thornton',
'Marrakesh' : 'Carrollton',
'Nagoya' : 'GreenBay',
'Los Angeles' : 'Stockton',
'Sendai' : 'Charleston',
'Kobe' : 'Flint',
'Chicago' : 'Grand Prairie',
'London' : 'Cedar Rapids',
'Gifu' : 'Miramar',
'Moncalvo' : 'Jersey City',
'Florence' : 'Brownsville',
'Istanbul' : 'Hesperia',
'Sao Paulo' : 'South Bend',
'damascus' : 'Santa Ana',
'Narita' : 'Redding',
'Buffalo' : 'Marina',
'Fukui' : 'Layton',
'Barcelona' : 'Richmond County',
'Oslo' : 'Utica',
'Munich' : 'Danbury',
'Vienna' : 'Fort Smith',
'Bombay' : 'Lowell',
'Maastricht' : 'Providence',
'Hiroshima' : 'Trenton',
'Salt Lake City' : 'Independence',
'Rome' : 'Huntington',
'São Paulo' : 'San Bernardino',
'Nara' : 'Bradenton',
'Paris' : 'Hollywood',
'hamburg' : 'Yonkers',
'Beijing' : 'Mesquite',
'Constantinople' : 'Mobile',
'Seattle' : 'Fitchburg',
'washington, d.c.' : 'Ontario',
'Kawasaki' : 'Nashville',
'Mexico' : 'Ogden',
'Kyoto' : 'Daytona Beach',
'Niigata' : 'Rochester',
'Baghdad' : 'Naperville',
'Melbourne' : 'Erie',
'Kinshasa' : 'Boise City',
'Leipzig' : 'Sacramento',
'Athens' : 'Palm Springs',
'San Jose' : 'Denver',
'Yokohama' : 'McAllen',
'Pretoria' : 'College Station',
'Urumqi' : 'Allentown',
'Tbilisi' : 'Houma',
'Portland' : 'Stamford',
'Buenos Aires' : 'Honolulu',
'Basra' : 'Pittsburgh',
'Babylon' : 'Lincoln',
'Hebron' : 'Palmdale',
'Kanazawa' : 'Columbus',
'Hanover' : 'Muskegon',
'Ooita' : 'Long Beach',
'Liverpool' : 'Duluth',
'Tokyo' : 'Nashua',
'Detroit' : 'Colorado Springs',
'York' : 'Westminster',
'Washington DC' : 'Round Lake Beach',
'Sapporo' : 'Pueblo',
'Venice' : 'Simi Valley',
'Alexandria' : 'Garland',
'Coventry' : 'Boulder',
'New Delhi' : 'Kailua',
'Cairo' : 'Little Rock',
'Pskov' : 'Anchorage',
'Tel Aviv' : 'Marysville',
'New Orleans' : 'Norwich',
'Fort Worth' : 'Bakersfield',
'San Francisco' : 'Rockford',
'New York' : 'McHenry',
'Moscow' : 'North Charleston',
'Berlin' : 'Sebastian',
'Madrid' : 'Des Moines',
'Boston' : 'Newburgh',
'Las Vegas' : 'Elkhart',
'Dallas' : 'West Covina',
'Mecca' : 'Lubbock',
'Rio de Janeiro' : 'Fayetteville',
'Aachen' : 'Topeka',
'Nagasaki' : 'Hialeah',
'Nantes' : 'Manchester',
'Hadley' : 'Barnstable',
'Vicksburg' : 'Wilmington',
'Shanghai' : 'Cincinnati',
'Belgium' : 'Sierra Leone',
'Japan' : 'South Korea',
'America' : 'Moldova',
'austria' : 'Antigua and Barbuda',
'Lebanon' : 'Cameroon',
'West Germany' : 'Burkina Faso',
'Scotland' : 'Samoa',
'Ukraine' : 'Bahamas',
'india' : 'Belize',
'america' : 'Belarus',
'netherlands' : 'Monaco',
'vietnam' : 'Bhutan',
'Peru' : 'United States of America',
'Malta' : 'Saint Vincent and the Grenadines',
'turkey' : 'Mauritius',
'Kazakhstan' : 'Haiti',
'croatia' : 'Niger',
'switzerland' : 'Hungary',
'Holland' : 'New Zealand',
'norway' : 'Angola',
'japan' : 'Palau',
#'Côte d'Ivoire' : 'Cyprus',
'algeria' : 'Montenegro',
'ireland' : 'Guyana',
'thailand' : 'Liberia',
'Azerbaijan' : 'Jordan',
'france' : 'Zimbabwe',
'Egypt' : 'Nicaragua',
'Ecuador' : 'Central African Republic',
'Andorra' : 'Jamaica',
'North Korea' : 'Costa Rica',
'england' : 'Suriname',
'Sri Lanka' : 'Uzbekistan',
'Romania' : 'Lesotho',
'Maldives' : 'Bulgaria',
'sweden' : 'Kosovo',
'korea' : 'Nauru',
'Thailand' : 'Ghana',
'britain' : 'Bangladesh',
'Greece' : 'Guinea-Bissau',
'Iran' : 'Solomon Islands',
'Russia' : 'Georgia',
'Korea' : 'Philippines',
'Chad' : 'Tuvalu',
'belgium' : 'Saint Lucia',
'canada' : 'Pakistan',
'Turkey' : 'Malawi',
'Australia' : 'Taiwan',
'Netherlands' : 'Nigeria',
'estonia' : 'Ethiopia',
'United States' : 'Mali',
'Mexico' : 'Bahrain',
'ethiopia' : 'Eritrea',
'France' : 'El Salvador',
'Singapore' : 'Vanuatu',
'Tanzania' : 'United Kingdom',
'China' : 'Benin',
'Spain' : 'Comoros',
'Indonesia' : 'Czechia',
'russia' : 'Eswatini',
'south africa' : 'Qatar',
'spain' : 'Luxembourg',
'Brazil' : 'Serbia',
'Iraq' : 'Estonia',
'Italy' : 'Kenya',
'hungary' : 'Grenada',
'Guatemala' : 'Liechtenstein',
'germany' : 'Bosnia and Herzegovina',
'Mauritania' : 'Laos',
'kenya' : 'Paraguay',
'colombia' : 'Slovakia',
'finland' : 'Senegal',
'poland' : 'North Macedonia',
'Bolivia' : 'South Sudan',
'Malaysia' : 'Finland',
'India' : 'Israel',
'Yugoslavia' : 'Lithuania',
'Syria' : 'Cambodia',
'Norway' : 'Gabon',
'Iceland' : 'Burundi',
'South Africa' : 'Rwanda',
'australia' : 'Yemen',
'china' : 'Honduras',
'Germany' : 'Vatican City',
'mongolia' : 'Seychelles',
'philippines' : 'Sudan',
'Vietnam' : 'Djibouti',
'Sweden' : 'Mongolia',
'Tunisia' : 'United Arab Emirates',
'Zambia' : 'Togo',
'Libya' : 'Micronesia',
'French' : 'Tonga',
'Switzerland' : 'Botswana',
'mexico' : 'Namibia',
'Afghanistan' : 'Palestine',
'Croatia' : 'Kiribati',
'Morocco' : 'Latvia',
'syria' : 'Mozambique',
'brazil' : 'Timor-Leste',
'Austria' : 'Denmark',
'Cuba' : 'Dominica',
'Poland' : 'Equatorial Guinea',
'Somalia' : 'Sao Tome and Principe',
'italy' : 'Uruguay',
'Algeria' : 'Kuwait',
'Zaire' : 'Trinidad and Tobago',
'united kingdom' : 'Guinea',
'egypt' : 'Brunei',
'England' : 'Gambia',
'Democratic Republic of the Congo' : 'Saudi Arabia',
'Canada' : 'Albania',
'Argentina' : 'San Marino',
'Portugal' : 'Cabo Verde',
'Ireland' : 'Turkmenistan',
'Pribilof Islands' : 'Mauritius',
'Taiwan' : 'Bahamas',
'St. Helena' : 'Santorini',
'Bali' : 'Tahiti',
'Sumatra' : 'Galapagos Islands',
'Okinawa' : 'Whitsunday Islands',
'hawaii' : 'The Azores',
'lesbos' : 'Bora Bora',
'Heligoland' : 'Fiji',
'Kyushu' : 'Bermuda',
'Elba' : 'Cayman Islands',
'Iceland' : 'Capri',
'Shikoku' : 'Seychelles',
'Corsica' : 'Phuket',
'Hokkaido' : 'British Virgin Islands',
'Bikini Atoll' : 'Corfu',
'Bavaria' : 'American Samoa',
'Connecticut' : 'Hawaii',
'Normandy' : 'Kentucky',
'Nebraska' : 'Virgin Islands',
'California' : 'Maryland',
'Massachusetts' : 'Vermont',
'Saskatchewan' : 'District',
'california' : 'New Hampshire',
'Ohio' : 'South Dakota',
'Texas' : 'Puerto Rico',
'bavaria' : 'New York',
'Michigan' : 'Florida',
'Illinois' : 'Virginia',
'New Yersey' : 'Wisconsin',
'Utah' : 'Missouri',
'Alsace' : 'Oregon',
'Louisiana' : 'Tennessee',
'Alaska' : 'Wyoming',
'North Carolina' : 'Mississippi',
'United States' : 'Kansas',
'India' : 'South Carolina',
'Rhode Island' : 'Montana',
'Japan' : 'of Columbia',
'America' : 'Guam',
'Scotland' : 'Idaho',
'Mexico' : 'New Mexico',
'Israel' : 'North Dakota',
'Britain' : 'Washington',
'Greece' : 'Iowa',
'Russia' : 'Pennsylvania',
'Finland' : 'Georgia',
'Argentina' : 'Oklahoma',
'Canada' : 'Minnesota',
'Germany' : 'New Jersey',
'Baker' : 'Charissa',
'Holy' : 'Bettina',
'Laurie' : 'Bobbie',
'Heather' : 'Elfie',
'Lucy' : 'Nadiya',
'Nancy Ianiero' : 'Delphine',
'Sylvia Costas' : 'Timmie',
'Anne' : 'Deerdre',
'Susan Greene' : 'Kaylyn',
'Millie' : 'Rhianna',
'Lori' : 'Sonni',
'Muiriel' : 'Georgianna',
'Virginia Woolf' : 'Jandy',
'Luna' : 'Devonna',
'Beth' : 'Charo',
'Leona Helmsley' : 'Jacky',
'Sappho' : 'Francoise',
'Mabel Normand' : 'Helsa',
'Odette' : 'Austina',
'Guinevere' : 'Celestine',
'Tusnelda' : 'Desaree',
'Alice' : 'Bendite',
'Eve' : 'Venita',
'Marie' : 'Jobie',
'Lidya' : 'Dollie',
'Ana' : 'Winifred',
#'Lupita Nyong'o' : 'Roanne',
'Judy' : 'Rey',
'Madonna' : 'Cristine',
'Rosa' : 'Stacee',
'Yoko' : 'Martie',
'Ellen' : 'Annabel',
'Joan' : 'Cassi',
'Marilyn Monroe' : 'Sheril',
'Barbara' : 'Jorie',
'Pua' : 'Clem',
'Carrie Tomlinson' : 'Stoddard',
'Snow White' : 'Selena',
'Melanie' : 'Allyce',
'Akira' : 'Candie',
'Betty' : 'Nonah',
'Agnès' : 'Adele',
'Amelia Earhart' : 'Willy',
'Yumi' : 'Mia',
'Chelsea' : 'Rosabel',
'Iva Majoli' : 'Tiffani',
'Emily' : 'Betteanne',
'Catherine the Great' : 'Carry',
'Kiesbauer' : 'Dacia',
'Tina Turner' : 'Kamilah',
'Laura' : 'Inna',
'Noriko' : 'Dyna',
'Jones' : 'Annissa',
'Hobday' : 'Glyn',
'Cristina' : 'Deny',
'Teresa' : 'Enya',
'Tracy' : 'Marinna',
'Jeannie' : 'Pauli',
'Linda' : 'Saree',
'Mae West' : 'Bernadette',
'Meg' : 'Dove',
'Ann' : 'Coriss',
'Hitomi' : 'Dacie',
'Natasha' : 'Fredra',
'Naoko' : 'Jacynth',
'Mayuko' : 'Chloe',
'Liisa' : 'Sabra',
'Kate' : 'Gaby',
'Margaret' : 'Candis',
'Marge' : 'Lurlene',
'Maria' : 'Joly',
'Jackson' : 'Faustine',
'Pearl Primus' : 'Dianemarie',
'Carla' : 'Willyt',
'Green' : 'Kiersten',
'Magdalena' : 'Anabella',
'Mary' : 'Felicity',
'Merry' : 'Stormy',
'Jane' : 'Remy',
'Karen' : 'Tresa',
'Valentina Tereshkova' : 'Cara',
'Kim' : 'Roselin',
'Yana' : 'Hetti',
'Patricia' : 'Melosa',
'Paola' : 'Elonore',
'Gracia' : 'Emmie',
'Helen' : 'Dannye',
'Sandra Goudie' : 'Ilyssa',
'Hanako' : 'Zuzana',
'Emi' : 'Bambie',
'Laura Ingalls' : 'Griselda',
'Sita' : 'Carri',
'Sylvia' : 'Teresina',
'Edith Piaf' : 'Gae',
'Miriam' : 'Ibby',
'Genevieve de Gaulle-Anthonics' : 'Codee',
'Sophie' : 'Adrea',
'Lady of the Lake' : 'Katha',
'Rodica' : 'Ameline',
'Marie Antoinette' : 'Norri',
'Ruth' : 'Brynne',
'Begum' : 'Belvia',
'Sue' : 'Angy',
'Simone Signoret' : 'Raquela',
'Lisa Lillien' : 'Konstanze',
'Sarah' : 'Sarajane',
'Kenza' : 'Elberta',
'Dale Evans' : 'Nixie',
'Lida' : 'Binny',
'Elena' : 'Rozalie',
'Hansson' : 'Shina',
'Anna' : 'Paige',
'Curtis' : 'Britt',
'Bruce' : 'Tandy',
'Julia' : 'Aleece',
'Sachiko' : 'Doria',
'Eva Peron' : 'Mariquilla',
'Elaine' : 'Lynsey',
'Sally' : 'Jaquenette',
'Britney Spears' : 'Nettle',
'Trang' : 'Fidelity',
'Patterson' : 'Sibilla',
'Lalita' : 'Jodee',
'Elizabeth' : 'Allianora',
'Kumi' : 'Dorena',
'Suzanne' : 'Sarina',
'Susan' : 'Nellie',
'Nancy' : 'Oralee',
'Gisèle' : 'Gloriane',
'Meryem' : 'Norean',
'Rachel Carson' : 'Cameo',
'Wendy' : 'Ashly',
'Aurelie' : 'Emlynn',
'Taninna' : 'Delia',
'Charlotte Brontë' : 'Flori',
'Ogawa' : 'Carmon',
'Dawson' : 'Morty',
'Chopin' : 'Ephraim',
'Bell' : 'Carleigh',
'Roger Vercel' : 'Brent',
'Costas Simitis' : 'Damian',
'Sherlock Holmes' : 'Abe',
'Kamal' : 'Salmon',
'Jesus' : 'Antoine',
'Marco Polo' : 'Natale',
'Lin Piao' : 'Charlton',
'Wood' : 'Emil',
'Burt Lancaster' : 'Ham',
'Stefan Edberg' : 'Laurent',
'Doi' : 'Elwin',
'Henry Ford' : 'Augustin',
'Charlie Chaplin' : 'Fraser',
'Walt Disney' : 'Virgilio',
'Piet Mondrian' : 'Hermy',
'Roy' : 'Niki',
'Jenninger' : 'Davin',
'Hawk' : 'Llewellyn',
'Mike' : 'Ali',
'Gerhard Sundt' : 'Pincus',
'Wilkins' : 'Aziz',
'Andres Escobar' : 'Esteban',
'George Washington' : 'Flemming',
'Filiberto' : 'Quent',
'Romano Prodi' : 'Jethro',
'Swift' : 'Mikel',
'Marco' : 'Yaakov',
'André Henri Constant van Hasselt' : 'Roderigo',
'Buzz Aldrin' : 'Dirk',
'St. John' : 'Wolfie',
'Bach' : 'Hewie',
'Brian' : 'Kory',
'Schubert' : 'Winford',
'Hitler' : 'Cobby',
'Julio' : 'Raleigh',
'Vance' : 'Cat',
'Ned' : 'Gardiner',
'Roosevelt' : 'Brendan',
'Robert Frost' : 'Thorn',
'Thomas Edison' : 'Tuckie',
'Edison' : 'Udale',
'Richard Roberts' : 'Michael',
'Evliya Celebi' : 'Bancroft',
'Chris' : 'Dov',
'Charles de Gaulle' : 'Olag',
'Leo Tolstoy' : 'Simeon',
'El-Nashar' : 'Avrom',
'Hughes' : 'Andy',
'Hashimoto' : 'Lefty',
'Harry Potter' : 'Walther',
'Becker' : 'Alix',
'Mifune' : 'Osmund',
'Bush' : 'Tibold',
'Justin Bieber' : 'Tanner',
'Nick' : 'Merell',
'Liu Bei' : 'Benjamin',
'Oleg' : 'Derrol',
'Aaron Copland' : 'Liam',
'John Dillinger' : 'Slade',
'Ricardo' : 'Forrest',
'Jiro' : 'Clay',
'Robert' : 'Mylo',
'Arthur' : 'Dickie',
'Edgar Degas' : 'Hashim',
'Ibrahim Sofu' : 'Ferguson',
'Raman Raghav' : 'Bret',
'Michael Crichton' : 'Wat',
'george walker bush' : 'Dwane',
'Brandon Lee' : 'Tynan',
'Naoki' : 'Jody',
'Bill Gates' : 'Ez',
'Avilov' : 'Sarge',
'Lancelot' : 'Tymon',
'Kieslowski' : 'Alden',
'Zola' : 'Brandon',
'Little Johnny' : 'Maxfield',
'clive staple lewis' : 'Shayne',
'Smith' : 'Norton',
'Baena Soares' : 'Godwin',
'Pierrot' : 'Haywood',
'Brian Eno' : 'Mitchael',
'Emet' : 'Gabriel',
'George' : 'Benjamen',
'Nelson Mandela' : 'Calvin',
'Anthony Blunt' : 'Jock',
'Rudolf' : 'Leif',
'Antonio' : 'Leighton',
'Tony Blair' : 'Dominic',
'Dan' : 'Ernie',
'Maciek' : 'Zeus',
'Keisuke' : 'Shurlock',
'Scrooge' : 'Reggie',
'Bob' : 'Garcia',
'Norman Finkelstein' : 'Antonino',
'Stephen Hawking' : 'Rory',
'Taro' : 'Barde',
'Taro Akagawa' : 'Tyrone',
'Bill' : 'Merrick',
'John Lennon' : 'Winslow',
'Schneider' : 'Park',
'Lopez' : 'Halvard',
'Stephen Harper' : 'Zeke',
'Fabio' : 'Lev',
'Keiko' : 'Siffre',
'Emil Fischer' : 'Maxie',
'Steve' : 'Saxon',
'Chabrol' : 'Valentin',
'Markku' : 'Tarrant',
'Peter' : 'Alton',
'René Capistran Garza' : 'Bartholomew',
'John Quincy Adams' : 'Johny',
'Frederick' : 'Ritchie',
'Ben' : 'Louis',
'Frederick West' : 'Arne',
'Niels Bohr' : 'Herschel',
'Jan De Bont' : 'Rutherford',
'Ford' : 'Eddie',
'Charles I' : 'Mohammed',
'Edward' : 'Magnum',
'Maurice Papon' : 'Nolan',
'Putin' : 'Tedie',
'Mel Karmazin' : 'Rabi',
'Sachiyo' : 'Helmuth',
'Nelson Beavers' : 'Chaim',
'Tycho Brahe' : 'Markos',
'Éamonn' : 'Kalil',
'Adolf Hitler' : 'Caleb',
'Rosario Ibarra' : 'Chad',
'Bob Marley' : 'Waring',
'Edvard Munch' : 'Tracie',
'Tom Jackson' : 'Roger',
'Gianni Versace' : 'Neil',
'Charles Dickens' : 'Tudor',
'Miguel Indurain' : 'Rudd',
'Brown' : 'Roarke',
'Paul' : 'Phineas',
'Napoleon' : 'Garey',
'Shinji Ono' : 'Dario',
'Michael Jackson' : 'Ozzie',
'Klaus Pohl' : 'Wynn',
'Leloir' : 'Gustavo',
'Alfred Nobel' : 'Tonnie',
'Ken' : 'Windham',
'Bill Clinton' : 'Sherlock',
'Carl Lewis' : 'Jerrome',
'Picasso' : 'Lindsey',
'Roger Miller' : 'Gonzales',
'Hans' : 'Eli',
'Saburo' : 'Hercules',
'Luke' : 'Kingsly',
'Achille' : 'Jerrold',
'Walt' : 'Connie',
'Eugenio Montale' : 'Uri',
'Andre Agassi' : 'Ambrosius',
'Rabin' : 'August',
'Daniel' : 'Simone',
'Obama' : 'Levy',
'Yoshio' : 'Donal',
'Vladislav Listyev' : 'Esau',
'Carl Smith' : 'Simon',
'Felipe González Márquez' : 'Waverley',
'Bob Dylan' : 'Talbert',
'Beethoven' : 'Lucian',
'Marilyn Manson' : 'Osmond',
'Jacques' : 'Chrisy',
'De Jong' : 'Bronson',
'Edgar Allen Poe' : 'Hunter',
'Maximilian' : 'Zary',
'Paolo' : 'Sayres',
'Johann Wolfgang von Goethe' : 'Lonny',
'Kim Il Sung' : 'Sheppard',
'Pedro' : 'Floyd',
'David Beckham' : 'Reynard',
'Sato' : 'Rod',
'Jack' : 'Jordy',
'Brett Favre' : 'Britt',
'Chen' : 'Sasha',
'Tom Kalinske' : 'Corrie',
'Tom Cruise' : 'Clem',
'Allan Chapman' : 'Wilfred',
'Muhammad Ali' : 'Michele',
'Jim' : 'Rich',
'Yamamoto' : 'Nikita',
'Einstein' : 'Albert',
'Luis' : 'Elisha',
'Tanaka' : 'Chan',
'Emile Zola' : 'Sheffie',
'Jerry Reinsdorf' : 'Robbert',
'Jorge' : 'Lamont',
'Joseph Wilson' : 'Hilbert',
'Thomas' : 'Wallace',
'Weinrich' : 'Sherwin',
'John Paul II' : 'Konstantin',
'Tyler Jackson' : 'Gav',
'Howard Caine' : 'Erek',
'Zhao' : 'Taylor',
'Hans Christian Anderson' : 'Wright',
'Samuel' : 'Zack',
'Munch' : 'Hurley',
'Castro' : 'Rolph',
'White' : 'Darby',
'Muhammed' : 'Rufe',
'Yamaha' : 'Marc',
'Alfredo Cristiani' : 'Quigly',
'Vlad the Impaler' : 'Remington',
'Wang' : 'Giordano',
'john fitzgerald kennedy' : 'Gerome',
'Cameron' : 'Jimmy',
'Lenz' : 'Rubin',
'Ramu' : 'Barton',
'Grant' : 'Dana',
'Leonardo da Vinci' : 'Billie',
'Harry' : 'Meredeth',
'Peter Jackson' : 'Glen',
'Rutherford Hayes' : 'Derron',
'Steven Jenkins' : 'Reece',
'George Wallace' : 'Wye',
'Anwar Sadat' : 'Bernhard',
'Liu Xiaobo' : 'Neel',
'Irving Mitchell Felt' : 'Rodger',
'Jerry Garcia' : 'Maddy',
'Berlioz' : 'Adolf',
'Mike Tyson' : 'Theo',
'Tom Hunter' : 'Ed',
'Ayrton Senna' : 'Ruddie',
'Saad Hariri' : 'Jerome',
'John Dalton' : 'Dominique',
'Gabriel Garcia Marquez' : 'Rene',
'Alexander the Great' : 'Pierre',
'Carl' : 'Heinrich',
'Ted' : 'Elijah',
'John' : 'Hank',
'Gian Antonio Maggi' : 'Sivert',
'Yunus' : 'Courtney',
'Goethe' : 'Patin',
'Lincoln' : 'Angelico',
'Brad Pitt' : 'Ervin',
'Freud' : 'Willmott',
'Qin Shi Huang' : 'Tally',
'Karim' : 'Angus',
'Keeton' : 'Prasad',
'Samir' : 'Xymenes',
'Joe' : 'Reginauld',
'Kennedy' : 'Van',
'Babe Ruth' : 'Olivier',
'Cat Stevens' : 'Cody',
'Pinocchio' : 'Saundra',
'Ichiro' : 'Harcourt',
'Clinton' : 'Allin',
'Nick Leeson' : 'Ossie',
'Yitzhak Rabin' : 'Ian',
'Brian Goodell' : 'Garry',
'Al Gore' : 'Tobie',
'Sam' : 'Chariot',
'Darwin' : 'Fabian',
'Napoleon Bonaparte' : 'Pepito',
'Hooper' : 'Weber',
'Gene Bartow' : 'Jean-Lou',
'Jyestadeva' : 'Dean',
'Marlowe' : 'Gardener',
'Ikeda' : 'Tyson',
'Mitt Romney' : 'Artur',
'Charlemagne' : 'Sutton',
'Frank' : 'Salvatore',
'Dick' : 'Ethelred',
'Keats' : 'Churchill',
'Andy Whitfield' : 'Sidnee',
'Elvis' : 'Martino',
'Edu' : 'Aldric',
'Warren Harding' : 'Sly',
'Mohamed Dib' : 'Esme',
'Lech' : 'Winfred',
'Alex Marcelo' : 'Gilbert',
'Louis Riel' : 'Kalvin',
'Michelangelo Antonioni' : 'Monty',
'Yamada' : 'Guillaume',
'Gottfried Reinhardt' : 'Agamemnon',
'Alexander Hamilton' : 'Archibald',
'Kerensky' : 'Walsh',
'Zinedine Zidane' : 'Patric',
'William Wallace' : 'Eustace',
'Tom' : 'Moishe',
'Frank Sinatra' : 'Wyndham',
'Nixon' : 'Justis',
'Javier' : 'Curtis',
'Chuck' : 'Vinnie',
'Deng Xiaoping' : 'Otho',
'Abrams' : 'Weidar',
'Mark' : 'Judd',
'Coleridge' : 'Alain',
'Tony' : 'Briggs',
'Alexander' : 'Kurtis',
'Quentin Tarantino' : 'Thorsten',
'James' : 'Noah'
}

# Define a regular expression pattern to match city urdu_names (both single and multi-word)
pattern = r'\b(?:' + '|'.join(re.escape(city) for city in city_mapping.keys()) + r')\b'

with open('../../tense_augmented_data/gold/tense_augmented_sbn_5.0/gold_tense_aug_x3.sbn', 'r') as main, open(
        '../../po_noun_with_tense_data/gold_po_noun_with_tense.sbn', 'w') as done:
    text = main.read()


    def replace_city(match):
        city = match.group()
        return city_mapping.get(city, city)


    # Use a function to replace the matched city name
    modified_text = re.sub(pattern, replace_city, text, flags=re.IGNORECASE)
    done.write(modified_text)