import re

city_mapping = {
    'Jerusalem' : 'Vienna',
'Osaka' : 'Berlin',
'Edo' : 'Fukui',
'Budapest' : 'Salt Lake City',
'Klagenfurt' : 'Oslo',
'Matsuyama' : 'Washington DC',
'Tehran' : 'Aachen',
'Lisbon' : 'Las Vegas',
'Marrakesh' : 'Hebron',
'Nagoya' : 'Tbilisi',
'Los Angeles' : 'Mexico',
'Sendai' : 'Rio de Janeiro',
'Kobe' : 'Rome',
'Chicago' : 'Lisbon',
'London' : 'Paris',
'Gifu' : 'New Delhi',
'Moncalvo' : 'Sapporo',
'Florence' : 'Nagasaki',
'Istanbul' : 'Ooita',
'Sao Paulo' : 'Detroit',
'damascus' : 'hamburg',
'Narita' : 'Florence',
'Buffalo' : 'Tel Aviv',
'Fukui' : 'Liverpool',
'Barcelona' : 'Basra',
'Oslo' : 'Gifu',
'Munich' : 'Leipzig',
'Vienna' : 'Vicksburg',
'Bombay' : 'Chicago',
'Maastricht' : 'Sao Paulo',
'Hiroshima' : 'Nantes',
'Salt Lake City' : 'Kawasaki',
'Rome' : 'Urumqi',
'São Paulo' : 'Los Angeles',
'Nara' : 'Marrakesh',
'Paris' : 'Munich',
'hamburg' : 'Hanover',
'Beijing' : 'Constantinople',
'Constantinople' : 'damascus',
'Seattle' : 'Niigata',
'washington, d.c.' : 'Kyoto',
'Kawasaki' : 'Babylon',
'Mexico' : 'Pretoria',
'Kyoto' : 'Portland',
'Niigata' : 'Venice',
'Baghdad' : 'New York',
'Melbourne' : 'Madrid',
'Kinshasa' : 'Istanbul',
'Leipzig' : 'New Orleans',
'Athens' : 'Klagenfurt',
'San Jose' : 'Alexandria',
'Yokohama' : 'Sendai',
'Pretoria' : 'Kobe',
'Urumqi' : 'York',
'Tbilisi' : 'Buenos Aires',
'Portland' : 'Barcelona',
'Buenos Aires' : 'Narita',
'Basra' : 'Athens',
'Babylon' : 'Kanazawa',
'Hebron' : 'Maastricht',
'Kanazawa' : 'Osaka',
'Hanover' : 'Moscow',
'Ooita' : 'Salt Lake City',
'Liverpool' : 'San Jose',
'Tokyo' : 'Fort Worth',
'Detroit' : 'Nara',
'York' : 'Cairo',
'Washington DC' : 'Buffalo',
'Sapporo' : 'Hiroshima',
'Venice' : 'New York',
'Alexandria' : 'Dallas',
'Coventry' : 'Budapest',
'New Delhi' : 'San Francisco',
'Cairo' : 'Edo',
'Pskov' : 'Coventry',
'Tel Aviv' : 'São Paulo',
'New Orleans' : 'Nagoya',
'Fort Worth' : 'Pskov',
'San Francisco' : 'Moncalvo',
'New York' : 'Seattle',
'Moscow' : 'London',
'Berlin' : 'washington, d.c.',
'Madrid' : 'Beijing',
'Boston' : 'Baghdad',
'Las Vegas' : 'Hadley',
'Dallas' : 'Yokohama',
'Mecca' : 'Jerusalem',
'Rio de Janeiro' : 'Tehran',
'Aachen' : 'Matsuyama',
'Nagasaki' : 'Mecca',
'Nantes' : 'Boston',
'Hadley' : 'Melbourne',
'Vicksburg' : 'Tokyo',
'Shanghai' : 'Shanghai',
'Belgium' : 'Singapore',
'Japan' : 'Iraq',
'America' : 'norway',
'austria' : 'mexico',
'Lebanon' : 'kenya',
'West Germany' : 'Austria',
'Scotland' : 'Scotland',
'Ukraine' : 'Sweden',
'india' : 'Zaire',
'america' : 'austria',
'netherlands' : 'Thailand',
'vietnam' : 'Peru',
'Peru' : 'brazil',
'Malta' : 'Vietnam',
'turkey' : 'France',
'Kazakhstan' : 'Mauritania',
'croatia' : 'Mexico',
'switzerland' : 'North Korea',
'Holland' : 'Malta',
'norway' : 'netherlands',
'japan' : 'Maldives',
#'Côte d'Ivoire' : 'French',
'algeria' : 'canada',
'ireland' : 'Switzerland',
'thailand' : 'Bolivia',
'Azerbaijan' : 'Indonesia',
'france' : 'Greece',
'Egypt' : 'russia',
'Ecuador' : 'Japan',
#'Andorra' : 'Côte d'Ivoire',
'North Korea' : 'Somalia',
'england' : 'Chad',
'Sri Lanka' : 'algeria',
'Romania' : 'Ecuador',
'Maldives' : 'japan',
'sweden' : 'Turkey',
'korea' : 'Iceland',
'Thailand' : 'Zambia',
'britain' : 'Iran',
'Greece' : 'Kazakhstan',
'Iran' : 'poland',
'Russia' : 'China',
'Korea' : 'germany',
'Chad' : 'Ireland',
'belgium' : 'Andorra',
'canada' : 'Romania',
'Turkey' : 'sweden',
'Australia' : 'Portugal',
'Netherlands' : 'spain',
'estonia' : 'united kingdom',
'United States' : 'switzerland',
'Mexico' : 'Australia',
'ethiopia' : 'ireland',
'France' : 'france',
'Singapore' : 'china',
'Tanzania' : 'Egypt',
'China' : 'Norway',
'Spain' : 'South Africa',
'Indonesia' : 'Malaysia',
'russia' : 'United States',
'south africa' : 'korea',
'spain' : 'England',
'Brazil' : 'Sri Lanka',
'Iraq' : 'Italy',
'Italy' : 'turkey',
'hungary' : 'Yugoslavia',
'Guatemala' : 'Poland',
'germany' : 'Guatemala',
'Mauritania' : 'belgium',
'kenya' : 'syria',
'colombia' : 'Russia',
'finland' : 'italy',
'poland' : 'Ukraine',
'Bolivia' : 'Germany',
'Malaysia' : 'Morocco',
'India' : 'vietnam',
'Yugoslavia' : 'india',
'Syria' : 'Tunisia',
'Norway' : 'australia',
'Iceland' : 'Canada',
'South Africa' : 'estonia',
'australia' : 'hungary',
'china' : 'Argentina',
'Germany' : 'West Germany',
'mongolia' : 'south africa',
'philippines' : 'Syria',
'Vietnam' : 'Azerbaijan',
'Sweden' : 'Algeria',
'Tunisia' : 'britain',
'Zambia' : 'mongolia',
'Libya' : 'Democratic Republic of the Congo',
'French' : 'Holland',
'Switzerland' : 'america',
'mexico' : 'colombia',
'Afghanistan' : 'Croatia',
'Croatia' : 'Belgium',
'Morocco' : 'Brazil',
'syria' : 'england',
'brazil' : 'Spain',
'Austria' : 'America',
'Cuba' : 'Libya',
'Poland' : 'India',
'Somalia' : 'finland',
'italy' : 'croatia',
'Algeria' : 'Lebanon',
'Zaire' : 'philippines',
'united kingdom' : 'ethiopia',
'egypt' : 'egypt',
'England' : 'Afghanistan',
'Democratic Republic of the Congo' : 'Korea',
'Canada' : 'Netherlands',
'Argentina' : 'Tanzania',
'Portugal' : 'thailand',
'Ireland' : 'Cuba',
'Pribilof Islands' : 'Sumatra',
'Taiwan' : 'Okinawa',
'St. Helena' : 'St. Helena',
'Bali' : 'Iceland',
'Sumatra' : 'Shikoku',
'Okinawa' : 'Hokkaido',
'hawaii' : 'Heligoland',
'lesbos' : 'hawaii',
'Heligoland' : 'Corsica',
'Kyushu' : 'Elba',
'Elba' : 'Kyushu',
'Iceland' : 'Taiwan',
'Shikoku' : 'Bali',
'Corsica' : 'Pribilof Islands',
'Hokkaido' : 'Bikini Atoll',
'Bikini Atoll' : 'lesbos',
'Dawson' : 'Alfredo Cristiani',
'Chopin' : 'Antonio',
'Bell' : 'Mark',
'Roger Vercel' : 'Bell',
'Costas Simitis' : 'Beethoven',
'Sherlock Holmes' : 'Tanaka',
'Kamal' : 'Henry Ford',
'Jesus' : 'Irving Mitchell Felt',
'Marco Polo' : 'Roger Vercel',
'Lin Piao' : 'Frank Sinatra',
'Wood' : 'Sam',
'Burt Lancaster' : 'Chabrol',
'Stefan Edberg' : 'Dick',
'Doi' : 'Paul',
'Henry Ford' : 'Charlemagne',
'Charlie Chaplin' : 'Gabriel Garcia Marquez',
'Walt Disney' : 'Freud',
'Piet Mondrian' : 'Alexander Hamilton',
'Roy' : 'Jacques',
'Jenninger' : 'john fitzgerald kennedy',
'Hawk' : 'Stephen Hawking',
'Mike' : 'Michelangelo Antonioni',
'Gerhard Sundt' : 'Brett Favre',
'Wilkins' : 'Edu',
'Andres Escobar' : 'Alfred Nobel',
'George Washington' : 'Hans Christian Anderson',
'Filiberto' : 'Liu Xiaobo',
'Romano Prodi' : 'Putin',
'Swift' : 'Qin Shi Huang',
'Marco' : 'Hooper',
'André Henri Constant van Hasselt' : 'Goethe',
'Buzz Aldrin' : 'Dawson',
'St. John' : 'Keeton',
'Bach' : 'Smith',
'Brian' : 'John Lennon',
'Schubert' : 'Stephen Harper',
'Hitler' : 'Wang',
'Julio' : 'Luis',
'Vance' : 'Kamal',
'Ned' : 'Yamaha',
'Roosevelt' : 'Abrams',
'Robert Frost' : 'clive staple lewis',
'Thomas Edison' : 'Karim',
'Edison' : 'Grant',
'Richard Roberts' : 'Klaus Pohl',
'Evliya Celebi' : 'Romano Prodi',
'Chris' : 'Lenz',
'Charles de Gaulle' : 'Jerry Garcia',
'Leo Tolstoy' : 'Fabio',
'El-Nashar' : 'Achille',
'Hughes' : 'Saad Hariri',
'Hashimoto' : 'Jerry Reinsdorf',
'Harry Potter' : 'Frederick West',
'Becker' : 'Darwin',
'Mifune' : 'Keats',
'Bush' : 'Maurice Papon',
'Justin Bieber' : 'Castro',
'Nick' : 'Al Gore',
'Liu Bei' : 'Ford',
'Oleg' : 'Pierrot',
'Aaron Copland' : 'Allan Chapman',
'John Dillinger' : 'Michael Jackson',
'Ricardo' : 'Stefan Edberg',
'Jiro' : 'Hans',
'Robert' : 'Burt Lancaster',
'Arthur' : 'Tony Blair',
'Edgar Degas' : 'Bill Clinton',
'Ibrahim Sofu' : 'Jyestadeva',
'Raman Raghav' : 'Marco',
'Michael Crichton' : 'Michael Crichton',
'george walker bush' : 'Johann Wolfgang von Goethe',
'Brandon Lee' : 'Zinedine Zidane',
'Naoki' : 'Saburo',
'Bill Gates' : 'Mel Karmazin',
'Avilov' : 'Brian',
'Lancelot' : 'Joseph Wilson',
'Kieslowski' : 'Becker',
'Zola' : 'Brandon Lee',
'Little Johnny' : 'Kennedy',
'clive staple lewis' : 'El-Nashar',
'Smith' : 'Jack',
'Baena Soares' : 'Bach',
'Pierrot' : 'René Capistran Garza',
'Brian Eno' : 'Scrooge',
'Emet' : 'George',
'George' : 'David Beckham',
'Nelson Mandela' : 'Tyler Jackson',
'Anthony Blunt' : 'Charles I',
'Rudolf' : 'Harry Potter',
'Antonio' : 'Edgar Degas',
'Tony Blair' : 'Gianni Versace',
'Dan' : 'Vladislav Listyev',
'Maciek' : 'Hitler',
'Keisuke' : 'Eugenio Montale',
'Scrooge' : 'Tom Jackson',
'Bob' : 'Nick',
'Norman Finkelstein' : 'Evliya Celebi',
'Stephen Hawking' : 'Buzz Aldrin',
'Taro' : 'Anwar Sadat',
'Taro Akagawa' : 'Gene Bartow',
'Bill' : 'Carl Smith',
'John Lennon' : 'Doi',
'Schneider' : 'Tom Hunter',
'Lopez' : 'Ken',
'Stephen Harper' : 'Miguel Indurain',
'Fabio' : 'Costas Simitis',
'Keiko' : 'Quentin Tarantino',
'Emil Fischer' : 'Keisuke',
'Steve' : 'Bob Dylan',
'Chabrol' : 'Chen',
'Markku' : 'Emet',
'Peter' : 'Bill',
'René Capistran Garza' : 'Charlie Chaplin',
'John Quincy Adams' : 'Leonardo da Vinci',
'Frederick' : 'Javier',
'Ben' : 'Cat Stevens',
'Frederick West' : 'Wilkins',
'Niels Bohr' : 'Alexander the Great',
'Jan De Bont' : 'De Jong',
'Ford' : 'Yamamoto',
'Charles I' : 'Zola',
'Edward' : 'Munch',
'Maurice Papon' : 'Bush',
'Putin' : 'Filiberto',
'Mel Karmazin' : 'Joe',
'Sachiyo' : 'Chopin',
'Nelson Beavers' : 'St. John',
'Tycho Brahe' : 'Tony',
'Éamonn' : 'Rosario Ibarra',
'Adolf Hitler' : 'Edward',
'Rosario Ibarra' : 'Muhammad Ali',
'Bob Marley' : 'Jan De Bont',
'Edvard Munch' : 'Walt',
'Tom Jackson' : 'Yitzhak Rabin',
'Gianni Versace' : 'Thomas',
'Charles Dickens' : 'Brad Pitt',
'Miguel Indurain' : 'Chuck',
'Brown' : 'Bob',
'Paul' : 'Éamonn',
'Napoleon' : 'Tycho Brahe',
'Shinji Ono' : 'Jim',
'Michael Jackson' : 'Weinrich',
'Klaus Pohl' : 'Howard Caine',
'Leloir' : 'Pinocchio',
'Alfred Nobel' : 'Bob Marley',
'Ken' : 'Robert Frost',
'Bill Clinton' : 'Edgar Allen Poe',
'Carl Lewis' : 'Schubert',
'Picasso' : 'Rutherford Hayes',
'Roger Miller' : 'Andre Agassi',
'Hans' : 'Luke',
'Saburo' : 'Andy Whitfield',
'Luke' : 'Lincoln',
'Achille' : 'Andres Escobar',
'Walt' : 'Lopez',
'Eugenio Montale' : 'Peter Jackson',
'Andre Agassi' : 'Oleg',
'Rabin' : 'Roosevelt',
'Daniel' : 'Jesus',
'Obama' : 'Avilov',
'Yoshio' : 'Sherlock Holmes',
'Vladislav Listyev' : 'William Wallace',
'Carl Smith' : 'Norman Finkelstein',
'Felipe González Márquez' : 'Frederick',
'Bob Dylan' : 'Anthony Blunt',
'Beethoven' : 'Frank',
'Marilyn Manson' : 'Tom Kalinske',
'Jacques' : 'Thomas Edison',
'De Jong' : 'George Washington',
'Edgar Allen Poe' : 'Ramu',
'Maximilian' : 'Marco Polo',
'Paolo' : 'Steven Jenkins',
'Johann Wolfgang von Goethe' : 'Nelson Beavers',
'Kim Il Sung' : 'Aaron Copland',
'Pedro' : 'Marlowe',
'David Beckham' : 'Jiro',
'Sato' : 'Kim Il Sung',
'Jack' : 'Ibrahim Sofu',
'Brett Favre' : 'Keiko',
'Chen' : 'Mohamed Dib',
'Tom Kalinske' : 'Alex Marcelo',
'Tom Cruise' : 'Vlad the Impaler',
'Allan Chapman' : 'Ikeda',
'Muhammad Ali' : 'Lech',
'Jim' : 'Edvard Munch',
'Yamamoto' : 'Taro Akagawa',
'Einstein' : 'Wood',
'Luis' : 'James',
'Tanaka' : 'Schneider',
'Emile Zola' : 'Tom',
'Jerry Reinsdorf' : 'Taro',
'Jorge' : 'Harry',
'Joseph Wilson' : 'Raman Raghav',
'Thomas' : 'John Quincy Adams',
'Weinrich' : 'Yoshio',
'John Paul II' : 'Chris',
'Tyler Jackson' : 'Hawk',
'Howard Caine' : 'Carl Lewis',
'Zhao' : 'White',
'Hans Christian Anderson' : 'Steve',
'Samuel' : 'Arthur',
'Munch' : 'Elvis',
'Castro' : 'Tom Cruise',
'White' : 'Marilyn Manson',
'Muhammed' : 'Kieslowski',
'Yamaha' : 'Lin Piao',
'Alfredo Cristiani' : 'Niels Bohr',
'Vlad the Impaler' : 'Bill Gates',
'Wang' : 'Gerhard Sundt',
'john fitzgerald kennedy' : 'Piet Mondrian',
'Cameron' : 'Cameron',
'Lenz' : 'Napoleon',
'Ramu' : 'Felipe González Márquez',
'Grant' : 'Pedro',
'Leonardo da Vinci' : 'Nelson Mandela',
'Harry' : 'Napoleon Bonaparte',
'Peter Jackson' : 'Emile Zola',
'Rutherford Hayes' : 'Leo Tolstoy',
'Steven Jenkins' : 'Babe Ruth',
'George Wallace' : 'Yunus',
'Anwar Sadat' : 'Roger Miller',
'Liu Xiaobo' : 'Maximilian',
'Irving Mitchell Felt' : 'Einstein',
'Jerry Garcia' : 'Clinton',
'Berlioz' : 'Rabin',
'Mike Tyson' : 'Walt Disney',
'Tom Hunter' : 'Hughes',
'Ayrton Senna' : 'Ayrton Senna',
'Saad Hariri' : 'Liu Bei',
'John Dalton' : 'Roy',
'Gabriel Garcia Marquez' : 'Edison',
'Alexander the Great' : 'Emil Fischer',
'Carl' : 'Coleridge',
'Ted' : 'John Dillinger',
'John' : 'Julio',
'Gian Antonio Maggi' : 'Samir',
'Yunus' : 'Nixon',
'Goethe' : 'Sato',
'Lincoln' : 'George Wallace',
'Brad Pitt' : 'Little Johnny',
'Freud' : 'Samuel',
'Qin Shi Huang' : 'Robert',
'Karim' : 'Kerensky',
'Keeton' : 'Louis Riel',
'Samir' : 'Jenninger',
'Joe' : 'Gian Antonio Maggi',
'Kennedy' : 'Ted',
'Babe Ruth' : 'george walker bush',
'Cat Stevens' : 'Justin Bieber',
'Pinocchio' : 'Alexander',
'Ichiro' : 'Brown',
'Clinton' : 'Ben',
'Nick Leeson' : 'Mitt Romney',
'Yitzhak Rabin' : 'Obama',
'Brian Goodell' : 'Nick Leeson',
'Al Gore' : 'Jorge',
'Sam' : 'Warren Harding',
'Darwin' : 'Naoki',
'Napoleon Bonaparte' : 'Baena Soares',
'Hooper' : 'André Henri Constant van Hasselt',
'Gene Bartow' : 'Brian Goodell',
'Jyestadeva' : 'Peter',
'Marlowe' : 'Sachiyo',
'Ikeda' : 'Richard Roberts',
'Mitt Romney' : 'Gottfried Reinhardt',
'Charlemagne' : 'Shinji Ono',
'Frank' : 'Hashimoto',
'Dick' : 'Maciek',
'Keats' : 'Lancelot',
'Andy Whitfield' : 'Ned',
'Elvis' : 'Picasso',
'Edu' : 'Charles Dickens',
'Warren Harding' : 'Carl',
'Mohamed Dib' : 'Swift',
'Lech' : 'John Dalton',
'Alex Marcelo' : 'Charles de Gaulle',
'Louis Riel' : 'Ricardo',
'Michelangelo Antonioni' : 'Muhammed',
'Yamada' : 'Vance',
'Gottfried Reinhardt' : 'Deng Xiaoping',
'Alexander Hamilton' : 'Zhao',
'Kerensky' : 'Markku',
'Zinedine Zidane' : 'Paolo',
'William Wallace' : 'Adolf Hitler',
'Tom' : 'Berlioz',
'Frank Sinatra' : 'Leloir',
'Nixon' : 'Mifune',
'Javier' : 'Yamada',
'Chuck' : 'Rudolf',
'Deng Xiaoping' : 'John',
'Abrams' : 'Mike Tyson',
'Mark' : 'Mike',
'Coleridge' : 'Daniel',
'Tony' : 'Ichiro',
'Alexander' : 'Dan',
'Quentin Tarantino' : 'Brian Eno',
'James' : 'John Paul II',
'Baker' : 'Edith Piaf',
'Holy' : 'Magdalena',
'Laurie' : 'Mabel Normand',
'Heather' : 'Aurelie',
'Lucy' : 'Agnès',
'Nancy Ianiero' : 'Kiesbauer',
'Sylvia Costas' : 'Ruth',
'Anne' : 'Marie',
'Susan Greene' : 'Rodica',
'Millie' : 'Yoko',
'Lori' : 'Maria',
'Muiriel' : 'Emily',
'Virginia Woolf' : 'Yana',
'Luna' : 'Emi',
'Beth' : 'Noriko',
'Leona Helmsley' : 'Cristina',
'Sappho' : 'Gisèle',
'Mabel Normand' : 'Jane',
'Odette' : 'Betty',
'Guinevere' : 'Lady of the Lake',
'Tusnelda' : 'Lori',
'Alice' : 'Holy',
'Eve' : 'Rosa',
'Marie' : 'Britney Spears',
'Lidya' : 'Luna',
'Ana' : 'Madonna',
#'Lupita Nyong'o' : 'Begum',
'Judy' : 'Taninna',
'Madonna' : 'Sylvia',
'Rosa' : 'Sachiko',
'Yoko' : 'Catherine the Great',
'Ellen' : 'Lucy',
'Joan' : 'Mary',
'Marilyn Monroe' : 'Millie',
'Barbara' : 'Muiriel',
'Pua' : 'Margaret',
'Carrie Tomlinson' : 'Lisa Lillien',
'Snow White' : 'Paola',
#'Melanie' : 'Lupita Nyong'o',
'Akira' : 'Liisa',
'Betty' : 'Marie Antoinette',
'Agnès' : 'Ann',
'Amelia Earhart' : 'Laura Ingalls',
'Yumi' : 'Elena',
'Chelsea' : 'Anna',
'Iva Majoli' : 'Naoko',
'Emily' : 'Trang',
'Catherine the Great' : 'Joan',
'Kiesbauer' : 'Simone Signoret',
'Tina Turner' : 'Marilyn Monroe',
'Laura' : 'Mayuko',
'Noriko' : 'Sue',
'Jones' : 'Pearl Primus',
'Hobday' : 'Odette',
'Cristina' : 'Yumi',
'Teresa' : 'Miriam',
'Tracy' : 'Guinevere',
'Jeannie' : 'Karen',
'Linda' : 'Snow White',
'Mae West' : 'Lalita',
'Meg' : 'Julia',
'Ann' : 'Tusnelda',
'Hitomi' : 'Leona Helmsley',
'Natasha' : 'Beth',
'Naoko' : 'Elaine',
'Mayuko' : 'Patterson',
'Liisa' : 'Chelsea',
'Kate' : 'Kumi',
'Margaret' : 'Jones',
'Marge' : 'Laura',
'Maria' : 'Sandra Goudie',
'Jackson' : 'Charlotte Brontë',
'Pearl Primus' : 'Tracy',
'Carla' : 'Sarah',
'Green' : 'Pua',
'Magdalena' : 'Sophie',
'Mary' : 'Merry',
'Merry' : 'Meg',
'Jane' : 'Susan',
'Karen' : 'Curtis',
'Valentina Tereshkova' : 'Ellen',
'Kim' : 'Sappho',
'Yana' : 'Mae West',
'Patricia' : 'Hanako',
'Paola' : 'Hobday',
'Gracia' : 'Kenza',
'Helen' : 'Meryem',
'Sandra Goudie' : 'Genevieve de Gaulle-Anthonics',
'Hanako' : 'Iva Majoli',
'Emi' : 'Lidya',
'Laura Ingalls' : 'Linda',
'Sita' : 'Eva Peron',
'Sylvia' : 'Akira',
'Edith Piaf' : 'Amelia Earhart',
'Miriam' : 'Alice',
'Genevieve de Gaulle-Anthonics' : 'Wendy',
'Sophie' : 'Tina Turner',
'Lady of the Lake' : 'Nancy',
'Rodica' : 'Virginia Woolf',
'Marie Antoinette' : 'Marge',
'Ruth' : 'Helen',
'Begum' : 'Susan Greene',
'Sue' : 'Kim',
'Simone Signoret' : 'Laurie',
'Lisa Lillien' : 'Barbara',
'Sarah' : 'Patricia',
'Kenza' : 'Ogawa',
'Dale Evans' : 'Rachel Carson',
'Lida' : 'Judy',
'Elena' : 'Bruce',
'Hansson' : 'Carrie Tomlinson',
'Anna' : 'Sylvia Costas',
'Curtis' : 'Heather',
'Bruce' : 'Gracia',
'Julia' : 'Dale Evans',
'Sachiko' : 'Valentina Tereshkova',
'Eva Peron' : 'Elizabeth',
'Elaine' : 'Kate',
'Sally' : 'Hitomi',
'Britney Spears' : 'Melanie',
'Trang' : 'Teresa',
'Patterson' : 'Baker',
'Lalita' : 'Jackson',
'Elizabeth' : 'Suzanne',
'Kumi' : 'Ana',
'Suzanne' : 'Sita',
'Susan' : 'Nancy Ianiero',
'Nancy' : 'Green',
'Gisèle' : 'Natasha',
'Meryem' : 'Anne',
'Rachel Carson' : 'Carla',
'Wendy' : 'Jeannie',
'Aurelie' : 'Lida',
'Taninna' : 'Hansson',
'Charlotte Brontë' : 'Sally',
'Ogawa' : 'Eve',
'Bavaria' : 'Britain',
'Connecticut' : 'America',
'Normandy' : 'Louisiana',
'Nebraska' : 'Alaska',
'California' : 'Scotland',
'Massachusetts' : 'Massachusetts',
'Saskatchewan' : 'Rhode Island',
'california' : 'India',
'Ohio' : 'North Carolina',
'Texas' : 'Alsace',
'bavaria' : 'Bavaria',
'Michigan' : 'Russia',
'Illinois' : 'Japan',
'New Yersey' : 'United States',
'Utah' : 'Michigan',
'Alsace' : 'Finland',
'Louisiana' : 'Greece',
'Alaska' : 'Texas',
'North Carolina' : 'bavaria',
'United States' : 'Argentina',
'India' : 'New Yersey',
'Rhode Island' : 'Saskatchewan',
'Japan' : 'Mexico',
'America' : 'Canada',
'Scotland' : 'Normandy',
'Mexico' : 'Germany',
'Israel' : 'United States',
'Britain' : 'Illinois',
'Greece' : 'Connecticut',
'Russia' : 'Israel',
'Finland' : 'california',
'Argentina' : 'California',
'Canada' : 'Nebraska',
'Germany' : 'Ohio'
}

# Define a regular expression pattern to match city urdu_names (both single and multi-word)
pattern = r'\b(?:' + '|'.join(re.escape(city) for city in city_mapping.keys()) + r')\b'

with open('../../gold_sbn_5.0/gold.sbn', 'r') as main, open(
        '../inside_context/p_nouns_from_sbn/gold_pi_noun_aug_dic_based.sbn', 'w') as done:
    text = main.read()


    def replace_city(match):
        city = match.group()
        return city_mapping.get(city, city)


    # Use a function to replace the matched city name
    modified_text = re.sub(pattern, replace_city, text, flags=re.IGNORECASE)
    done.write(modified_text)