# import nltk
# from nltk.corpus import wordnet
# import re
# import random
#
# nltk.download('wordnet')
# #
# # # Manually curated list of antonyms (add your own)
# # manual_antonyms = {
# #     "shocked": ['unsurprised'],
# #     "allergic": ['immune', 'resistant', 'unresponsive'],
# #     "favorite": ['disliked', 'unpopular', 'least-favorite'],
# #     "naked": ['clothed'],
# #     "unbeatable": ['beatable'],
# #     "amused": ['bored'],
# #     "amazing": ['ordinary'],
# #     "old-fashioned": ['modern'],
# #     "puzzled": ['clear'],
# #     "riveting": ['boring'],
# #     "homesick": ['content'],
# #     "paraplegic": ['able-bodied'],
# #     "messy": ['tidy'],
# #     "absurd": ['logical'],
# #     "disgusted": ['pleased'],
# #     "laid-back": ['uptight'],
# #     "heartbroken": ['elated'],
# #     "astonished": ['unsurprised'],
# #     "excellent": ['poor'],
# #     "proficient": ['inexperienced'],
# #     "not_guilty": ['guilty'],
# #     "commonplace": ['extraordinary'],
# #     "according": ['disagreeing'],
# #     "orange": ['non-orange'],
# #     "famous": ['unknown'],
# #     "magnificent": ['ordinary'],
# #     "shaky": ['stable'],
# #     "worn_out": ['refreshed'],
# #     "shaken": ['steady'],
# #     "fed_up": ['satisfied'],
# #     "aspiring": ['settled'],
# #     "anxious": ['calm'],
# #     "acquainted": ['unfamiliar'],
# #     "sore": ['painless'],
# #     "silent": ['noisy'],
# #     "self-proclaimed": ['humble'],
# #     "scared": ['brave'],
# #     "upper": ['lower'],
# #     "sunny": ['cloudy'],
# #     "ruined": ['restored'],
# #     "manipulative": ['honest'],
# #     "dizzy": ['steady'],
# #     "deadly": ['harmless'],
# #     "tiny": ['huge'],
# #     "outraged": ['pleased'],
# #     "mad": ['sane'],
# #     "overdue": ['early'],
# #     "risky": ['safe'],
# #     "purple": ['non-purple'],
# #     "frustrated": ['satisfied'],
# #     "frantic": ['calm'],
# #     "groggy": ['alert'],
# #     "two-faced": ['genuine'],
# #     "newborn": ['mature'],
# #     "smashed": ['intact'],
# #     "autobiographical": ['fictional'],
# #     "dumb": ['intelligent'],
# #     "defective": ['flawless'],
# #     "stressful": ['relaxing'],
# #     "well-known": ['obscure'],
# #     "world-wide": ['local'],
# #     "out_of_print": ['in-print'],
# #     "beige": ['colorful'],
# #     "nonsense": ['sense'],
# #     "waterproof": ['non-waterproof'],
# #     "understanding": ['misunderstanding'],
# #     "brown": ['non-brown'],
# #     "utter": ['partial'],
# #     "olympic": ['non-olympic'],
# #     "orphaned": ['parented'],
# #     "silly": ['serious'],
# #     "notorious": ['unknown'],
# #     "lucrative": ['unprofitable'],
# #     "huge": ['tiny'],
# #     "ancient": ['modern'],
# #     "deserted": ['populated'],
# #     "inseparable": ['separable'],
# #     "drunken": ['sober'],
# #     "magic": ['mundane'],
# #     "unimpressed": ['impressed'],
# #     "overweight": ['underweight'],
# #     "middle-aged": ['young'],
# #     "anorexic": ['healthy'],
# #     "merry": ['sad'],
# #     "neck_and_neck": ['unequal'],
# #     "indie": ['mainstream'],
# #     "prone": ['averse'],
# #     "state": ['unsettle'],
# #     "hallucinating": ['sane'],
# #     "hesitant": ['confident'],
# #     "grey": ['colorful'],
# #     "in_effect": ['ineffective'],
# #     "decapitated": ['intact'],
# #     "final": ['initial'],
# #     "gullible": ['skeptical'],
# #     "terrible": ['wonderful'],
# #     "booked": ['available'],
# #     "mediocre": ['exceptional'],
# #     "exhausting": ['energizing'],
# #     "teenage": ['adult'],
# #     "terrifying": ['comforting'],
# #     "exceptional": ['average'],
# #     "insolent": ['respectful'],
# #     "humiliating": ['uplifting'],
# #     "ajar": ['closed'],
# #     "skillful": ['unskilled'],
# #     "horrified": ['delighted'],
# #     "great": ['terrible'],
# #     "lesbian": ['heterosexual'],
# #     "secret": ['open'],
# #     "vigorous": ['feeble'],
# #     "scary": ['comforting'],
# #     "jealous": ['content'],
# #     "antique": ['modern'],
# #     "bright_blue": ['dull'],
# #     "unperturbed": ['disturbed'],
# #     "ruling": ['subject'],
# #     "located": ['misplaced'],
# #     "suspicious": ['trusting'],
# #     "fierce": ['gentle'],
# #     "over": ['under'],
# #     "fabulous": ['ordinary'],
# #     "innovative": ['conventional'],
# #     "unbiased": ['biased'],
# #     "epic": ['ordinary'],
# #     "close_at_hand": ['distant'],
# #     "mistaken": ['correct'],
# #     "ironic": ['straightforward'],
# #     "economical": ['extravagant'],
# #     "sleepy": ['awake'],
# #     "yellow": ['non-yellow'],
# #     "futile": ['effective'],
# #     "disappointed": ['satisfied'],
# #     "dyslexic": ['fluent'],
# #     "conceited": ['humble'],
# #     "undiscovered": ['well-known'],
# #     "dumbfounded": ['unsurprised'],
# #     "arcane": ['well-known'],
# #     "chestnut": ['non-chestnut'],
# #     "delicious": ['unappetizing'],
# #     "headstrong": ['flexible'],
# #     "irrefutable": ['debatable'],
# #     "smashing": ['failure'],
# #     "rare": ['common'],
# #     "handsome": ['ugly'],
# #     "total": ['partial'],
# #     "recent": ['ancient'],
# #     "outstanding": ['mediocre'],
# #     "faded": ['vibrant'],
# #     "lazy": ['diligent'],
# #     "hazel": ['non-hazel'],
# #     "outdated": ['modern'],
# #     "empathetic": ['indifferent'],
# #     "biased": ['unbiased'],
# #     "good-for-nothing": ['valuable'],
# #     "parliamentary": ['autocratic'],
# #     "venomous": ['harmless'],
# #     "charming": ['repulsive'],
# #     "gorgeous": ['ugly'],
# #     "countless": ['finite'],
# #     "in_love": ['indifferent'],
# #     "fake": ['genuine'],
# #     "hereditary": ['acquired'],
# #     "boastful": ['humble'],
# #     "awesome": ['awful'],
# #     "all_right": ['terrible'],
# #     "excruciating": ['bearable'],
# #     "handicapped": ['able-bodied'],
# #     "vital": ['trivial'],
# #     "swarthy": ['pale'],
# #     "sticky": ['slippery'],
# #     "bilingual": ['monolingual'],
# #     "wealthy": ['impoverished'],
# #     "cozy": ['uncomfortable'],
# #     "arrogant": ['humble'],
# #     "pink": ['non-pink'],
# #     "first-class": ['low-class'],
# #     "about": ['definite'],
# #     "roasted": ['raw'],
# #     "escaped": ['captured'],
# #     "divorced": ['married'],
# #     "decayed": ['fresh'],
# #     "wounded": ['uninjured'],
# #     "corporate": ['individual'],
# #     "bulky": ['compact'],
# #     "man-made": ['natural'],
# #     "blue": ['non-blue'],
# #     "ok": ['terrible'],
# #     "at_large": ['captured'],
# #     "diaphanous": ['opaque'],
# #     "economic": ['extravagant'],
# #     "elder": ['younger'],
# #     "paralyzed": ['mobile'],
# #     "gray-haired": ['young'],
# #     "nuts": ['sane'],
# #     "agog": ['indifferent'],
# #     "crimson": ['pale'],
# #     "electronic": ['analog'],
# #     "poisonous": ['harmless'],
# #     "aristocratic": ['common'],
# #     "crazy": ['sane'],
# #     "adjacent": ['distant'],
# #     "wonderful": ['terrible'],
# #     "light-blue": ['dark'],
# #     "embarrassed": ['confident'],
# #     "athletic": ['unathletic'],
# #     "entire": ['partial'],
# #     "nervous": ['calm'],
# #     "southeastern": ['northwestern'],
# #     "cute": ['ugly'],
# #     "excessive": ['moderate'],
# #     "shabby": ['stylish'],
# #     "stocky": ['slender'],
# #     "pathetic": ['impressive'],
# #     "lonely": ['accompanied'],
# #     "tired_of": ['enthusiastic_about'],
# #     "splendid": ['ordinary'],
# #     "pedantic": ['relaxed'],
# #     "top-secret": ['public'],
# #     "used_to": ['unfamiliar_with'],
# #     "abhorrent": ['admirable'],
# #     "polluted": ['clean'],
# #     "hammered": ['sober'],
# #     "various": ['identical'],
# #     "angelic": ['devilish'],
# #     "cynical": ['optimistic'],
# #     "obscene": ['decent'],
# #     "baffled": ['certain'],
# #     "iron": ['fragile'],
# #     "confusing": ['clear'],
# #     "tragic": ['joyful'],
# #     "abysmal": ['excellent'],
# #     "wooden": ['flexible'],
# #     "abandoned": ['inhabited'],
# #     "bright-red": ['dull'],
# #     "stoned": ['sober'],
# #     "northeastern": ['southwestern'],
# #     "tipsy": ['sober'],
# #     "creepy": ['comforting'],
# #     "funny": ['serious'],
# #     "salted": ['unsalted'],
# #     "weird": ['normal'],
# #     "belligerent": ['peaceful'],
# #     "expert": ['novice'],
# #     "vulgar": ['refined'],
# # }
#
# def find_antonym(word):
#     antonyms = []
#     for syn in wordnet.synsets(word):
#         for lemma in syn.lemmas():
#             if lemma.antonyms():
#                 antonyms.append(lemma.antonyms()[0].name())
#     return antonyms
#
# def is_adjective_in_text(word, text):
#     # Generate possible forms of the word
#     forms = set()
#     forms.add(word.lower())  # Lower-case
#     forms.add(word.upper())  # Upper-case
#     forms.add(word.capitalize())  # Cap-case
#
#     # Check if any form of the word is present in the text
#     for form in forms:
#         if form in text.lower():
#             return True
#     return False
#
# def replace_adjectives(sentence, logical_representation):
#     # Tokenize the sentence
#     tokens = nltk.word_tokenize(sentence)
#
#     # Extract adjectives from the logical representation for all possible senses (from .a.01 to .a.09)
#     logical_adjectives = []
#     for sense in range(1, 10):  # Iterate from .a.01 to .a.09
#         logical_adjectives += [word.split('.')[0] for word in logical_representation.split() if
#                               word.endswith(f'.a.{sense:02d}')]
#
#     # Replace adjectives
#     replaced_sentence = sentence
#
#     for word in logical_adjectives:
#         if is_adjective_in_text(word, sentence):
#             antonyms = find_antonym(word)
#
#             # Use a manually curated list if available
#             #if word in manual_antonyms:
#             #    antonyms.extend(manual_antonyms[word])
#
#             if antonyms:
#                 antonym = random.choice(antonyms)
#                 # Replace adjectives in both case-sensitive and case-insensitive forms
#                 replaced_sentence = replaced_sentence.replace(word, antonym)
#                 replaced_sentence = replaced_sentence.replace(word.capitalize(), antonym.capitalize())
#                 logical_representation = logical_representation.replace(word, antonym)
#
#     return replaced_sentence, logical_representation
#
# # Read the dataset from "gold_train.sbn"
# input_filename = "gold_train.sbn"
# output_filename = "adverb_replacement_with_antonyms_x1.sbn"
#
# with open(input_filename, "r") as infile:
#     lines = infile.readlines()
#
# # Perform adjective replacement and save the output
# replaced_dataset = []
#
# for line in lines:
#     sentence, logical_representation = line.strip().split('\t')
#     replaced_sentence, replaced_logical_representation = replace_adjectives(sentence,
#                                                                            logical_representation)
#     replaced_dataset.append((replaced_sentence, replaced_logical_representation))
#
# # Save the output to "adjective_replacement_with_antonyms_x1.sbn"
# with open(output_filename, "w") as outfile:
#     for sentence, logical_representation in replaced_dataset:
#         outfile.write(f"{sentence}\t{logical_representation}\n")

import nltk
import random
from nltk.corpus import wordnet
import re
nltk.download('wordnet')

manual_synonyms = {
    ##### GOLD Adverbs
    "somewhat": ["slightly", "a little", "moderately"],
    "away": ["gone", "absent", "off"],
    "bareback": ["without a saddle", "unmounted"],
    "all_of_a_sudden": ["suddenly"],
    "all of a sudden": ["suddenly"],
    "on board": ["aboard"],
    "on_board": ["aboard"],
    "sweetly": ["pleasantly", "charmingly", "nicely"],
    "wrong": ["incorrectly", "mistakenly", "erroneously"],
    "so": ["very", "extremely", "exceedingly"],
    "bitterly": ["angrily", "resentfully", "acrimoniously"],
    "just": ["only", "merely", "simply"],
    "barely": ["scarcely", "hardly", "just"],
    "directly": ["immediately", "straightaway", "promptly"],
    "clearly": ["plainly", "evidently", "obviously"],
    "a_bit": ["slightly"],
    "a bit": ["slightly"],
    "thoughtfully": ["considerately", "attentively", "reflectively"],
    "apart": ["separately", "individually", "asunder"],
    "badly": ["poorly", "ineffectively", "insufficiently"],
    "out of the blue": ["unexpectedly"],
    "out_of_the_blue": ["unexpectedly"],
    "in_common": ["collectively"],
    "in common": ["collectively"],
    "askance": ["suspiciously", "skeptically", "doubtfully"],
    "suspiciously": ["distrustfully", "skeptically", "warily"],
    "greatly": ["significantly", "enormously", "markedly"],
    "narrowly": ["barely", "closely", "tightly"],
    "beautifully": ["gorgeously", "wonderfully", "exquisitely"],
    "stark": ["completely", "entirely", "utterly"],
    "too": ["excessively", "overly", "excessively"],
    "officially": ["formally", "bureaucratically", "legally"],
    "low": ["lowly", "unpretentious", "modestly"],
    "voraciously": ["greedily", "ravenously", "hungrily"],
    "inside_out": ["entirely"],
    "inside out": ["entirely"],
    "easily": ["effortlessly", "comfortably", "smoothly"],
    "fully": ["completely", "entirely", "totally"],
    "very": ["extremely", "exceedingly", "incredibly"],
    "immediately": ["instantly", "promptly", "directly"],
    "face to face": ["personally"],
    "face_to_face": ["personally"],
    "suddenly": ["abruptly", "unexpectedly", "all of a sudden"],
    "well": ["healthy", "in good health", "sound"],
    "aboard": ["on board", "on ship", "on deck"],
    "sort_of": ["kind_of"],
    "sort of": ["kind of"],
    "dead": ["deceased", "lifeless", "deceased"],
    "from_time_to_time": ["occasionally"],
    "from time to time": ["occasionally"],
    "most": ["very", "extremely", "supremely"],
    "bravely": ["courageously", "valiantly", "heroically"],
    "deeply": ["profoundly", "intensely", "profoundly"],
    "merely": ["only", "just", "simply"],
    "hard": ["difficultly", "laboriously", "strenuously"],
    "highly": ["very", "extremely", "exceedingly"],
    "in_effect": ["essentially"],
    "in effect": ["essentially"],
    "carefully": ["cautiously", "prudently", "attentively"],
    "as": ["equally", "likewise", "similarly"],
    "extremely": ["exceedingly", "incredibly", "exceptionally"],
    "seriously": ["earnestly", "sincerely", "gravely"],
    "comfortably": ["cozily", "snugly", "pleasantly"],
    "automatically": ["spontaneously", "involuntarily", "reflexively"],
    "thoroughly": ["completely", "entirely", "totally"],
    "super": ["very", "extremely", "incredibly"],
    "back": ["backward", "rearward", "behind"],
    "hysterically": ["frantically", "uncontrollably", "wildly"],
    "terribly": ["horribly", "dreadfully", "awfully"],
    "grossly": ["flagrantly", "egregiously", "glaringly"],
    "in_public": ["openly"],
    "in public": ["openly"],
    "brightly": ["brilliantly", "vividly", "radiantly"],
    "secretly": ["covertly", "discreetly", "clandestinely"],
    "straight": ["directly", "in a straight line", "evenly"],
    "abreast": ["alongside", "side by side", "together"],
    "tightly": ["firmly", "securely", "closely"],
    "less": ["lesser", "not as much", "not so"],
    "really": ["truly", "genuinely", "actually"],
    "gracefully": ["elegantly", "gracefully", "beautifully"],
    "quickly": ["rapidly", "swiftly", "speedily"],
    "instantly": ["immediately", "promptly", "directly"],
    "more": ["additionally", "further", "moreover"],
    "across": ["over", "through", "spanning"],
    "quietly": ["silently", "noiselessly", "softly"],
    "a_little": ["a_bit"],
    "a little": ["a bit"],
    "visibly": ["noticeably", "clearly", "distinctly"],
    "much": ["a lot", "greatly", "significantly"],
    "girlishly": ["youthfully", "childishly", "naively"],
    "certainly": ["definitely", "surely", "absolutely"],
    "curiously": ["inquisitively", "inquiringly", "wonderingly"],
    "loudly": ["noisily", "audibly", "boisterously"],
    "safely": ["securely", "harmlessly", "without danger"],
    "alas": ["regrettably", "unfortunately", "sorrowfully"],
    "out": ["outside", "outdoors", "away"],
    "widely": ["broadly", "extensively", "universally"],
    "upwards": ["upward", "upwardly", "in an upward direction"],
    "heavily": ["densely", "weightily", "massively"],
    "calmly": ["tranquilly", "peacefully", "serenely"],
    "gruesomely": ["horrifyingly", "shockingly", "dreadfully"],
    "at_any_rate": ["nevertheless"],
    "at any rate": ["nevertheless"],
    "more_or_less": ["approximately"],
    "more or less": ["approximately"],
    "posthumously": ["after death", "mortuarily", "posthumously"],
    "all_at_once": ["suddenly"],
    "all at once": ["suddenly"],
    "gently": ["softly", "tenderly", "mildly"],
    "hesitantly": ["uncertainly", "tentatively", "reluctantly"],
    "slightly": ["somewhat", "a little", "marginally"],
    "scantily": ["sparsely", "meagerly", "barely"],
    "by_heart": ["by_memory"],
    "by heart": ["by memory"],
    "politely": ["courteously", "respectfully", "mannerly"],
    "pretty": ["rather", "quite", "fairly"],
    "all": ["everything", "every bit", "everything considered"],
    "mentally": ["intellectually", "cerebrally", "cognitively"],
    "completely": ["entirely", "wholly", "fully"],
    "after_all": ["nevertheless"],
    "after all": ["nevertheless"],
    "partially": ["partly", "incompletely", "fractionally"],
    "rather": ["quite", "somewhat", "fairly"],
    "furiously": ["angrily", "wrathfully", "fiercely"],
    "temporarily": ["briefly", "for a short time", "momentarily"],
    "usually": ["generally", "typically", "normally"],
    "silently": ["quietly", "noiselessly", "mutely"],
    "quite": ["rather", "fairly", "somewhat"],
    "head_over_heels": ["passionately"],
    "head over heels": ["passionately"],
    "bright": ["radiant", "luminous", "gleaming"],
    "totally": ["completely", "entirely", "wholly"],
    "hopelessly": ["despairingly", "forlornly", "irretrievably"],
    "kind_of": ["sort_of"],
    "kind of": ["sort of"],

    ###### SILVER Adverbss

"differently": ["distinctly", "otherwise", "unlike"],
    "big": ["large", "huge", "enormous"],
    "remarkably": ["notably", "significantly", "unusually"],
    "strange": ["unusual", "odd", "peculiar"],
    "inside": ["within", "internally", "indoors"],
    "meanwhile": ["in the meantime", "at the same time", "simultaneously"],
    "common": ["ordinary", "typical", "usual"],
    "following": ["subsequent", "succeeding", "next"],
    "in_other_words": ["to put it differently", "in simpler terms", "to clarify"],
    "wonderfully": ["beautifully", "excellently", "splendidly"],
    "wildly": ["frantically", "madly", "crazily"],
    "at_any_rate": ["anyhow", "in any case", "regardless"],
    "eminently": ["notably", "exceedingly", "remarkably"],
    "soon": ["shortly", "promptly", "before long"],
    "reportedly": ["allegedly", "apparently", "supposedly"],
    "alive": ["living", "vibrant", "animated"],
    "intensely": ["intensely", "deeply", "fiercely"],
    "lively": ["animated", "vibrant", "energetic"],
    "superciliously": ["arrogantly", "haughtily", "condescendingly"],
    "late": ["tardy", "belatedly", "after hours"],
    "lazily": ["indolently", "sluggishly", "lethargically"],
    "presidential": ["presidentially", "executive", "official"],
    "only": ["solely", "exclusively", "just"],
    "pretty": ["beautifully", "attractively", "lovely"],
    "good": ["well", "excellently", "admirably"],
    "real": ["genuine", "authentic", "actual"],
    "in_fact": ["actually", "indeed", "in reality"],
    "tonight": ["this evening", "tonight", "this night"],
    "sadly": ["unhappily", "regrettably", "unfortunately"],
    "suddenly": ["abruptly", "unexpectedly", "all of a sudden"],
    "dirt": ["soil", "earth", "filth"],
    "please": ["kindly", "please", "if you please"],
    "significantly": ["notably", "importantly", "remarkably"],
    "incorrectly": ["wrongly", "erroneously", "inaccurately"],
    "on": ["upon", "on top of", "above"],
    "vastly": ["immensely", "greatly", "exceedingly"],
    "patent": ["clear", "evident", "obvious"],
    "or_syllabic": ["alternatively", "orally", "syllabically"],
    "merrily": ["cheerfully", "happily", "joyfully"],
    "chronically": ["persistently", "constantly", "continually"],
    "simply": ["plainly", "simply", "just"],
    "nuclear": ["atomic", "nuclear", "atomic energy"],
    "helpless": ["powerless", "vulnerable", "defenseless"],
    "substantially": ["significantly", "considerably", "materially"],
    "war": ["conflict", "battle", "warfare"],
    "literally": ["verbatim", "exactly", "word for word"],
    "firmly": ["securely", "strongly", "steadfastly"],
    "strictly": ["rigidly", "severely", "stringently"],
    "live": ["alive", "living", "existing"],
    "occupational": ["professional", "work-related", "job-related"],
    "far": ["distant", "remote", "far-off"],
    "perfectly": ["flawlessly", "impeccably", "perfectly"],
    "throw": ["toss", "cast", "throw away"],
    "funny": ["amusing", "humorous", "comical"],
    "would": ["might", "could", "shall"],
    "desperately": ["urgently", "frantically", "earnestly"],
    "finally": ["ultimately", "eventually", "in the end"],
    "artistic": ["creative", "artful", "expressive"],
    "well": ["adequately", "properly", "effectively"],
    "refer": ["allude", "mention", "cite"],
    "identically": ["exactly", "precisely", "identically"],
    "continually": ["constantly", "incessantly", "persistently"],
    "role": ["function", "position", "duty"],
    "globally": ["worldwide", "internationally", "globally"],
    "etcetera": ["and so on", "and so forth", "etc."],
    "precisely": ["exactly", "accurately", "precisely"],
    "disparagingly": ["derisively", "contemptuously", "mockingly"],
    "flexibly": ["adaptable", "versatile", "pliably"],
    "doubtless": ["undoubtedly", "certainly", "assuredly"],
    "islamic": ["Islamic", "Muslim", "Islamist"],
    "actually": ["truly", "in reality", "indeed"],
    "grimly": ["sternly", "austere", "dour"],
    "secondary": ["second", "subordinate", "minor"],
    "adversely": ["negatively", "unfavorably", "detrimentally"],
    "hastily": ["quickly", "hurriedly", "rashly"],
    "freshly": ["newly", "recently", "just"],
    "seemingly": ["apparently", "ostensibly", "evidently"],
    "spiritually": ["religiously", "ethically", "morally"],
    "particularily": ["especially", "particularly", "specifically"],
    "organic": ["natural", "biological", "organic"],
    "afterward": ["subsequently", "later", "after"],
    "serious": ["grave", "earnest", "solemn"],
    "sort_of": ["kind of", "somewhat", "to some extent"],
    "automotive": ["vehicular", "motor", "auto"],
    "already": ["previously", "before", "prior"],
    "by_heart": ["by memory", "by rote", "by recall"],
    "briskly": ["energetically", "briskly", "vigorously"],
    "merely": ["simply", "only", "just"],
    "ridiculously": ["absurdly", "laughably", "preposterously"],
    "overly": ["excessively", "unduly", "too much"],
    "exceptionally": ["extraordinarily", "remarkably", "unusually"],
    "federal": ["national", "central", "governmental"],
    "in": ["inside", "within", "inward"],
    "supported": ["backed", "aided", "assisted"],
    "service": ["assistance", "help", "aid"],
    "mortally": ["fatally", "lethally", "deadly"],
    "scornfully": ["contemptuously", "derisively", "disdainfully"],
    "wily": ["cunningly", "craftily", "slyly"],
    "residential": ["domestic", "residing", "housing"],
    "particularly": ["especially", "notably", "specifically"],
    "politely": ["courteously", "graciously", "polished"],
    "daily": ["everyday", "daily", "day by day"],
    "civilian": ["non-military", "non-combatant", "civilian"],
    "narrowly": ["closely", "barely", "narrowly"],
    "wrongfully": ["unjustly", "unlawfully", "illegally"],
    "agrochemical": ["agricultural", "chemical", "pesticide"],
    "bang": ["loud noise", "explosion", "burst"],
    "awfully": ["terribly", "dreadfully", "horribly"],
    "convincingly": ["persuasively", "compellingly", "powerfully"],
    "open": ["unlocked", "unclosed", "openly"],
    "large": ["big", "huge", "enormous"],
    "largely": ["mostly", "mainly", "primarily"],
    "deep": ["profound", "deep-seated", "intense"],
    "securely": ["safely", "firmly", "securely"],
    "medical": ["health-related", "medical", "clinical"],
    "loosely": ["tightly", "slackly", "loosely"],
    "dangerously": ["hazardously", "risky", "perilously"],
    "satisfactory": ["acceptable", "sufficient", "adequate"],
    "southern": ["southerly", "southward", "southern"],
    "less": ["fewer", "not as much", "lower"],
    "administration_federal": ["federal administration", "government"],
    "seriously": ["earnestly", "sincerely", "gravely"],
    "permanent": ["lasting", "enduring", "permanent"],
    "trustworthy": ["reliable", "dependable", "trustworthy"],
    "slyly": ["cunningly", "craftily", "slyly"],
    "positively": ["affirmatively", "definitely", "positively"],
    "fine": ["excellent", "good", "fine"],
    "sleepless": ["insomniac", "awake", "sleepless"],
    "today": ["this day", "nowadays", "today"],
    "periodically": ["at intervals", "regularly", "periodically"],
    "illegal": ["unlawful", "illegitimate", "illegal"],
    "dead": ["lifeless", "deceased", "dead"],
    "harmlessly": ["innocuously", "safely", "harmlessly"],
    "easy": ["simple", "effortless", "easy"],
    "honestly": ["truthfully", "sincerely", "honestly"],
    "suitably": ["appropriately", "properly", "suitably"],
    "cruelly": ["inhumanely", "brutally", "cruelly"],
    "temporarily": ["briefly", "short-term", "temporarily"],
    "underground": ["subterranean", "below ground", "underground"],
    "short": ["brief", "briefly", "short"],
    "permit": ["allow", "authorize", "permit"],
    "understandably": ["clearly", "naturally", "understandably"],
    "heavenly": ["divine", "celestial", "heavenly"],
    "worthwhile": ["worth it", "rewarding", "beneficial"],
    "acrylic": ["plastic", "synthetic", "acrylic"],
    "basically": ["fundamentally", "essentially", "basically"],
    "sternly": ["firmly", "strictly", "sternly"],
    "otherwise": ["or else", "alternatively", "otherwise"],
    "generic": ["general", "common", "generic"],
    "cheerfully": ["happily", "joyfully", "cheerfully"],
    "very": ["extremely", "exceedingly", "very"],
    "dark": ["dim", "shadowy", "dark"],
    "online": ["on the internet", "web-based", "online"],
    "asap": ["as soon as possible", "quickly", "promptly"],
    "annually": ["yearly", "annually", "every year"],
    "essentially": ["fundamentally", "essentially", "basically"],
    "northwest": ["northwestern", "northwesterly", "northwest"],
    "site": ["location", "place", "site"],
    "simultaneously": ["at the same time", "concurrently", "simultaneously"],
    "perpendicularly": ["vertically", "upright", "perpendicularly"],
    "corporate": ["business", "corporate", "company"],
    "entirely": ["completely", "wholly", "entirely"],
    "different": ["distinct", "unique", "different"],
    "indelibly": ["permanently", "indelibly", "unforgettably"],
    "ideologically": ["philosophically", "ideologically", "theoretically"],
    "retroactively": ["retrospectively", "retroactively", "backward"],
    "supremely": ["extremely", "supremely", "exceedingly"],
    "grammatically": ["linguistically", "grammatically", "language-wise"],
    "southwest": ["southwestern", "southwesterly", "southwest"],
    "worth": ["value", "worth", "importance"],
    "down": ["below", "downward", "down"],
    "šmíd": ["Šmíd", "surname", "family name"],
    "islamist": ["Islamic", "Islamist", "Muslim"],
    "consistently": ["steadily", "consistently", "regularly"],
    "alone": ["solitary", "lonely", "alone"],
    "intricately": ["complexly", "intricately", "complicatedly"],
    "enthusiastically": ["eagerly", "enthusiastically", "keenly"],
    "gentlemen": ["gentlemen", "gentlefolk", "sirs"],
    "time": ["period", "time", "era"],
    "unsuccessfully": ["unsuccessfully", "ineffectively", "unsuccessfully"],
    "category": ["class", "category", "group"],
    "incidentally": ["by the way", "casually", "incidentally"],
    "nearby": ["close by", "near", "adjacent"],
    "crudely": ["roughly", "crudely", "primitively"],
    "right_away": ["immediately", "right away", "promptly"],
    "uncompromisingly": ["rigidly", "uncompromisingly", "inflexibly"],
    "porous": ["permeable", "porous", "penetrable"],
    "stateless": ["without a state", "stateless", "nationless"],
    "primarily": ["chiefly", "mainly", "primarily"],
    "neighbour": ["neighbor", "neighbour", "local resident"],
    "away": ["far away", "distant", "away"],
    "temporary": ["transient", "temporary", "short-term"],
    "enough": ["sufficiently", "adequately", "enough"],
    "extraordinarily": ["remarkably", "exceptionally", "extraordinarily"],
    "satisfied": ["content", "satisfied", "pleased"],
    "unbearably": ["intolerably", "unbearably", "excruciatingly"],
    "on_board": ["aboard", "on board", "onboard"],
    "out": ["outside", "outdoors", "out"],
    "professional": ["expert", "professional", "specialist"],
    "virtually": ["almost", "practically", "virtually"],
    "minimum": ["lowest", "minimum", "smallest"],
    "heavy": ["weighty", "heavy", "massive"],
    "polypropylene": ["plastic", "polypropylene", "synthetic resin"],
    "chiefly": ["mainly", "chiefly", "mostly"],
    "agree": ["concur", "agree", "consent"],
    "a_posteriori": ["deductive", "a posteriori", "inductive"],
    "fully": ["completely", "fully", "thoroughly"],
    "lightly": ["gently", "lightly", "softly"],
    "sub_rosa": ["secretly", "covertly", "sub rosa"],
    "curly": ["wavy", "curly", "twisted"],
    "formerly": ["previously", "formerly", "once"],
    "anywhere": ["everywhere", "anywhere", "wherever"],
    "marvellously": ["wonderfully", "marvelously", "fantastically"],
    "east": ["eastern", "easterly", "east"],
    "further": ["additional", "further", "beyond"],
    "crucially": ["vitally", "crucially", "decisively"],
    "compare": ["contrast", "compare", "examine"],
    "digital": ["electronic", "digital", "computerized"],
    "unbelievably": ["incredibly", "unbelievably", "amazingly"],
    "pleasantly": ["enjoyably", "pleasantly", "agreeably"],
    "unwittingly": ["unintentionally", "unwittingly", "unknowingly"],
    "socially": ["culturally", "socially", "societally"],
    "automatic": ["automated", "automatic", "self-regulating"],
    "sparsely": ["scarcely", "sparsely", "thinly"],
    "plainly": ["clearly", "plainly", "evidently"],
    "efficient": ["effective", "efficient", "productive"],
    "politically": ["governmentally", "politically", "officially"],
    "oncurrently": ["simultaneously", "concurrently", "at the same time"],
    "dreadfully": ["terribly", "dreadfully", "horribly"],
    "advanced": ["progressive", "advanced", "modern"],
    "closely": ["intimately", "closely", "near"],
    "irrespective": ["regardless", "irrespective", "independent of"],
    "major": ["significant", "major", "important"],
    "imply": ["suggest", "imply", "hint"],
    "carefully": ["cautiously", "carefully", "prudently"],
    "coldly": ["unemotionally", "coldly", "indifferently"],
    "ballistic": ["explosive", "ballistic", "rocket"],
    "uniquely": ["distinctively", "uniquely", "individually"],
    "that": ["that", "it", "this"],
    "minimal": ["minimal", "minimalistic", "bare minimum"],
    "moderately": ["reasonably", "moderately", "fairly"],
    "back": ["backward", "back", "rearward"],
    "holy": ["sacred", "holy", "divine"],
    "severely": ["harshly", "severely", "sternly"],
    "modestly": ["humbly", "modestly", "unpretentiously"],
    "oriented": ["focused", "oriented", "directed"],
    "right": ["correct", "right", "proper"],
    "busy": ["occupied", "busy", "engaged"],
    "biological": ["organic", "biological", "life-related"],
    "mutually": ["reciprocally", "mutually", "jointly"],
    "inexorably": ["relentlessly", "inexorably", "unyieldingly"],
    "kind": ["kind", "benevolent", "gentle"],
    "inseparably": ["indivisibly", "inseparably", "inextricably"],
    "centrally": ["central", "centrally", "core"],
    "head_over_heels": ["madly", "passionately", "head over heels"],
    "to": ["toward", "to", "into"],
    "while": ["whilst", "while", "meanwhile"],
    "so": ["therefore", "so", "thus"],
    "sexually": ["erotically", "sexually", "intimately"],
    "industrial": ["manufacturing", "industrial", "factory"],
    "widely": ["broadly", "widely", "extensively"],
    "therefore": ["thus", "therefore", "consequently"],
    "openly": ["publicly", "openly", "frankly"],
    "veritably": ["truly", "really", "veritably"],
    "intellectual": ["cerebral", "intellectual", "mental"],
    "reasonably": ["moderately", "reasonably", "fairly"],
    "noticeably": ["evidently", "noticeably", "apparently"],
    "critically": ["crucially", "critically", "vital"],
    "ostensibly": ["seemingly", "ostensibly", "apparently"],
    "_way": ["_way", "direction", "route"],
    "inversely": ["oppositely", "inversely", "contrarily"],
    "grand": ["impressive", "grand", "magnificent"],
    "person": ["individual", "person", "human"],
    "leading": ["foremost", "leading", "primary"],
    "intellectually": ["mentally", "intellectually", "cognitively"],
    "wounded": ["injured", "wounded", "hurt"],
    "seldom": ["rarely", "seldom", "infrequently"],
    "over": ["above", "over", "beyond"],
    "summarily": ["briskly", "briefly", "summarily"],
    "after_all": ["in the end", "after all", "ultimately"],
    "unarmed": ["disarmed", "unarmed", "weaponless"],
    "nowise": ["in no way", "nowise", "not at all"],
    "hugely": ["enormously", "hugely", "immensely"],
    "mostly": ["mainly", "mostly", "largely"],
    "closer": ["nearer", "closer", "near"],
    "municipal": ["local", "municipal", "city"],
    "local": ["community", "local", "municipal"],
    "outward": ["external", "outward", "outside"],
    "almost": ["nearly", "almost", "practically"],
    "quite": ["fairly", "quite", "rather"],
    "western": ["western", "westward", "occidental"],
    "infinitely": ["endlessly", "infinitely", "limitlessly"],
    "inside_out": ["inside out", "thoroughly", "completely"],
    "make": ["create", "make", "produce"],
    "first_off": ["initially", "first off", "to start"],
    "piss": ["urinate", "piss", "pee"],
    "profoundly": ["deeply", "profoundly", "intensely"],
    "any": ["any", "some", "whatever"],
    "incredibly": ["amazingly", "incredibly", "unbelievably"],
    "wholly": ["completely", "entirely", "wholly"],
    "economically": ["financially", "economically", "monetarily"],
    "visually": ["sight-wise", "visually", "aesthetically"],
    "critical": ["crucial", "critical", "essential"],
    "tournament": ["competition", "tournament", "contest"],
    "occasionally": ["sometimes", "occasionally", "from time to time"],
    "purely": ["completely", "purely", "entirely"],
    "considerably": ["significantly", "considerably", "substantially"],
    "entry": ["entrance", "entry", "access"],
    "vacation": ["holiday", "vacation", "break"],
    "sweet": ["sugary", "sweet", "pleasant"],
    "five": ["five", "5", "quint"],
    "just": ["merely", "just", "simply"],
    "causally": ["causally", "accidentally", "randomly"],
    "little": ["small", "little", "tiny"],
    "vocational": ["occupational", "vocational", "professional"],
    "about": ["concerning", "about", "regarding"],
    "southeast": ["southeastern", "southeasterly", "southeast"],
    "reliably": ["dependably", "reliably", "trustworthily"],
    "electrical": ["electric", "electrical", "powered"],
    "joint": ["shared", "joint", "combined"],
    "heartily": ["warmly", "heartily", "cordially"],
    "sometime": ["at some point", "sometime", "eventually"],
    "pharmaceutical": ["medicinal", "pharmaceutical", "medical"],
    "poorly": ["badly", "poorly", "inadequately"],
    "predominately": ["mostly", "mainly", "predominately"],
    "include": ["incorporate", "include", "encompass"],
    "respective": ["individual", "respective", "particular"],
    "bilingual": ["multilingual", "bilingual", "two-language"],
    "prehistoric": ["ancient", "prehistoric", "primeval"],
    "freely": ["openly", "freely", "willingly"],
    "en_route": ["on the way", "en route", "while traveling"],
    "inward": ["inward", "toward the inside", "internal"],
    "nationalistic": ["patriotic", "nationalistic", "jingoistic"],
    "special": ["unique", "special", "distinctive"],
    "a_little": ["somewhat", "a little", "to some extent"],
    "thermal": ["heat-related", "thermal", "temperature"],
    "accordingly": ["consequently", "accordingly", "thus"],
    "great": ["excellent", "great", "superb"],
    "contemptuously": ["disdainfully", "contemptuously", "scornfully"],
    "left": ["remaining", "left", "remaining"],
    "speedily": ["quickly", "speedily", "rapidly"],
    "categorically": ["unequivocally", "categorically", "definitely"],
    "trilogy": ["series of three", "trilogy", "three-part"],
    "far_eastern": ["eastern", "far eastern", "oriental"],
    "desperate": ["hopeless", "desperate", "dire"],
    "genetic": ["hereditary", "genetic", "inherited"],
    "stupid": ["foolish", "stupid", "ridiculous"],
    "abruptly": ["suddenly", "abruptly", "unexpectedly"],
    "allegedly": ["supposedly", "allegedly", "reportedly"],
    "unlawfully": ["illegally", "unlawfully", "wrongfully"],
    "medically": ["physically", "medically", "clinically"],
    "precious": ["valuable", "precious", "cherished"],
    "normally": ["usually", "normally", "typically"],
    "famously": ["well-known", "famously", "renowned"],
    "unusually": ["abnormally", "unusually", "extraordinarily"],
    "private": ["personal", "private", "individual"],
    "eventually": ["ultimately", "finally", "eventually"],
    "foreign": ["international", "foreign", "overseas"],
    "amazingly": ["incredibly", "amazingly", "astonishingly"],
    "damn": ["cursed", "damn", "accursed"],
    "now_and_then": ["occasionally", "now and then", "from time to time"],
    "double": ["twice", "double", "two times"],
    "boldly": ["bravely", "boldly", "courageously"],
    "illegally": ["unlawfully", "illegally", "wrongfully"],
    "generally": ["usually", "generally", "broadly"],
    "aboard": ["on board", "aboard", "onboard"],
    "cute": ["adorable", "cute", "charming"],
    "all": ["every", "all", "each"],
    "raw": ["uncooked", "raw", "natural"],
    "correspondingly": ["similarly", "correspondingly", "analogously"],
    "nationally": ["countrywide", "nationally", "nationwide"],
    "acid": ["sour", "acidic", "acid"],
    "partially": ["partly", "partially", "in part"],
    "entity": ["being", "entity", "existence"],
    "from": ["from", "out of", "away from"],
    "thus": ["therefore", "thus", "consequently"],
    "due": ["owing to", "due", "because of"],
    "central": ["central", "centralized", "core"],
    "richly": ["abundantly", "richly", "lavishly"],
    "state": ["condition", "state", "status"],
    "loyally": ["faithfully", "loyally", "devotedly"],
    "okay": ["alright", "okay", "fine"],
    "because": ["since", "because", "as"],
    "long": ["lengthy", "long", "extended"],
    "according": ["in accordance with", "according", "following"],
    "fire_directly": ["shoot", "fire directly", "open fire"],
    "constantly": ["continuously", "constantly", "unceasingly"],
    "uncontrollably": ["involuntarily", "uncontrollably", "helplessly"],
    "lovely": ["beautiful", "lovely", "charming"],
    "quick": ["fast", "quick", "swift"],
    "happily": ["joyfully", "happily", "cheerfully"],
    "european_social": ["European", "European Social", "European Socialist"],
    "catastrophic": ["disastrous", "catastrophic", "tragic"],
    "in_public": ["publicly", "in public", "openly"],
    "ensure": ["guarantee", "ensure", "assure"],
    "notably": ["especially", "notably", "particularly"],
    "nearly": ["almost", "nearly", "approximately"],
    "socialist": ["social", "socialist", "collectivist"],
    "thereby": ["thus", "thereby", "consequently"],
    "suspect": ["doubtful", "suspect", "questionable"],
    "unfortunately": ["regrettably", "unfortunately", "sadly"],
    "competent": ["capable", "competent", "skilled"],
    "pale": ["light", "pale", "fair"],
    "individually": ["separately", "individually", "one by one"],
    "newly": ["recently", "newly", "freshly"],
    "outstandingly": ["exceptionally", "outstandingly", "remarkably"],
    "thermally": ["heat-related", "thermally", "temperature"],
    "risky": ["dangerous", "risky", "hazardous"],
    "similarly": ["likewise", "similarly", "in the same way"],
    "ranging": ["spanning", "ranging", "extending"],
    "free": ["liberated", "free", "unrestricted"],
    "electrically": ["electronically", "electrically", "electric"],
    "highly": ["very", "highly", "extremely"],
    "absolutely": ["completely", "absolutely", "utterly"],
    "grossly": ["flagrantly", "grossly", "outrageously"],
    "cleverly": ["intelligently", "cleverly", "smartly"],
    "specifically": ["explicitly", "specifically", "precisely"],
    "single": ["individual", "single", "solitary"],
    "hard": ["difficult", "hard", "challenging"],
    "slowly": ["gradually", "slowly", "steadily"],
    "ok": ["okay", "ok", "alright"],
    "dramatically": ["drastically", "dramatically", "radically"],
    "miraculously": ["amazingly", "miraculously", "incredibly"],
    "definitively": ["conclusively", "definitively", "decisively"],
    "terminally": ["fatally", "terminally", "incurably"],
    "automatically": ["involuntarily", "automatically", "spontaneously"],
    "economic": ["financial", "economic", "monetary"],
    "strongly": ["forcefully", "strongly", "vigorously"],
    "deterministic": ["predictable", "deterministic", "inevitable"],
    "steadily": ["consistently", "steadily", "regularly"],
    "strategically": ["tactically", "strategically", "logistically"],
    "correctly": ["accurately", "correctly", "precisely"],
    "deliriously": ["ecstatically", "deliriously", "madly"],
    "wire": ["cable", "wire", "cord"],
    "horizontal": ["level", "horizontal", "flat"],
    "totally": ["completely", "totally", "entirely"],
    "in_common": ["shared", "common", "in common"],
    "baltic": ["Baltic", "Baltic Sea", "Baltic region"],
    "later": ["subsequent", "later", "afterward"],
    "objectively": ["impartially", "objectively", "neutrally"],
    "forward": ["ahead", "forward", "onward"],
    "fatally": ["mortally", "fatally", "lethally"],
    "bad": ["poor", "bad", "inferior"],
    "urgently": ["immediately", "urgently", "promptly"],
    "geographically": ["spatially", "geographically", "topographically"],
    "than": ["compared to", "than", "rather than"],
    "political": ["governmental", "political", "politic"],
    "carelessly": ["recklessly", "carelessly", "negligently"],
    "through": ["via", "through", "by means of"],
    "least": ["minimal", "least", "smallest"],
    "rapidly": ["quickly", "rapidly", "swiftly"],
    "excessively": ["unduly", "excessively", "immoderately"],
    "regular": ["standard", "regular", "normal"],
    "of_course": ["certainly", "of course", "undoubtedly"],
    "immediately": ["instantly", "immediately", "promptly"],
    "abroad": ["overseas", "abroad", "in a foreign country"],
    "easily": ["effortlessly", "easily", "readily"],
    "traditionally": ["customarily", "traditionally", "conventionally"],
    "hardly": ["barely", "hardly", "scarcely"],
    "insofar": ["to the extent that", "insofar", "to the degree that"],
    "round": ["circular", "round", "spherical"],
    "hazardous": ["dangerous", "hazardous", "risky"],
    "environmentally": ["ecologically", "environmentally", "greenly"],
    "asleep": ["unconscious", "asleep", "in a deep sleep"],
    "arrest": ["apprehend", "arrest", "seize"],
    "accidentally": ["inadvertently", "accidentally", "unintentionally"],
    "beautiful": ["attractive", "beautiful", "lovely"],
    "nervously": ["anxiously", "nervously", "tensely"],
    "clear": ["transparent", "clear", "crystal clear"],
    "privately": ["secretly", "privately", "confidentially"],
    "forestry": ["forestation", "forestry", "timberland"],
    "last": ["final", "last", "ultimate"],
    "kilometer": ["km", "kilometer", "klick"],
    "coil": ["spiral", "coil", "helix"],
    "contemporary": ["modern", "contemporary", "current"],
    "match": ["game", "match", "contest"],
    "fairly": ["justly", "fairly", "equitably"],
    "wrong": ["incorrect", "wrong", "inaccurate"],
    "quietly": ["silently", "quietly", "peacefully"],
    "fluently": ["articulately", "fluently", "eloquently"],
    "best": ["finest", "best", "superior"],
    "sick": ["ill", "sick", "unwell"],
    "dangerous": ["hazardous", "dangerous", "risky"],
    "rather": ["somewhat", "rather", "fairly"],
    "supposedly": ["allegedly", "supposedly", "reportedly"],
    "republican": ["GOP", "Republican", "right-wing"],
    "shortly": ["soon", "shortly", "briefly"],
    "first_motogp": ["initial", "first MotoGP", "premier"],
    "before": ["prior to", "before", "ahead of"],
    "somewhat": ["to some extent", "somewhat", "partly"],
    "now": ["currently", "now", "at present"],
    "commercial": ["business", "commercial", "trade"],
    "likely": ["probably", "likely", "possibly"],
    "eastern": ["east", "eastern", "oriental"],
    "true": ["accurate", "true", "correct"],
    "who": ["whom", "who", "which"],
    "thinly": ["sparsely", "thinly", "scantily"],
    "historically": ["traditionally", "historically", "over time"],
    "passionately": ["intensely", "passionately", "fervently"],
    "previously": ["formerly", "previously", "before"],
    "straight": ["direct", "straight", "undeviating"],
    "jolly": ["merry", "jolly", "cheerful"],
    "whitely": ["palely", "whitely", "ashen"],
    "subsequently": ["later", "subsequently", "afterward"],
    "hysterically": ["frantically", "hysterically", "wildly"],
    "fundamentally": ["essentially", "fundamentally", "basically"],
    "systematically": ["methodically", "systematically", "orderly"],
    "glad": ["happy", "glad", "pleased"],
    "north": ["northern", "north", "northerly"],
    "indirectly": ["implicitly", "indirectly", "tacitly"],
    "negligibly": ["minimally", "negligibly", "insignificantly"],
    "labour": ["work", "labour", "employment"],
    "cautiously": ["carefully", "cautiously", "prudently"],
    "in_turn": ["successively", "in turn", "sequentially"],
    "chemically": ["in terms of chemistry", "chemically", "elementally"],
    "legally": ["lawfully", "legally", "judicially"],
    "tomorrow": ["the next day", "tomorrow", "the following day"],
    "once": ["one time", "once", "formerly"],
    "vainly": ["futilely", "vainly", "fruitlessly"],
    "voilà": ["there you have it", "voilà", "behold"],
    "wide": ["broad", "wide", "spacious"],
    "selectively": ["discriminatorily", "selectively", "choosily"],
    "apparently": ["seemingly", "apparently", "ostensibly"],
    "technologically": ["technologically", "technically", "scientifically"],
    "presumably": ["supposedly", "presumably", "likely"],
    "dissolutely": ["immorally", "dissolutely", "licentiously"],
    "glyoxylic": ["glyoxylic", "glyoxyl"],
    "calm": ["tranquil", "calm", "serene"],
    "remain": ["stay", "remain", "linger"],
    "domestic": ["home", "domestic", "household"],
    "recently": ["lately", "recently", "of late"],
    "technical": ["technological", "technical", "engineering"],
    "obviously": ["clearly", "obviously", "evidently"],
    "financial": ["monetary", "financial", "economic"],
    "respectively": ["individually", "respectively", "each"],
    "prematurely": ["early", "prematurely", "untimely"],
    "primitively": ["primarily", "primitively", "elementarily"],
    "hotly": ["passionately", "hotly", "intensely"],
    "strangely": ["oddly", "strangely", "curiously"],
    "most": ["mostly", "most", "chiefly"],
    "across": ["over", "across", "throughout"],
    "rental": ["leasing", "rental", "hiring"],
    "internal": ["inner", "internal", "inside"],
    "culturally": ["socially", "culturally", "ethnically"],
    "equally": ["evenly", "equally", "uniformly"],
    "accept": ["receive", "accept", "take"],
    "negatively": ["adversely", "negatively", "unfavorably"],
    "swiftly": ["quickly", "swiftly", "rapidly"],
    "electric": ["electric", "electrically", "electrical"],
    "directly": ["immediately", "directly", "straight"],
    "new": ["recent", "new", "modern"],
    "headfirst": ["headlong", "headfirst", "diving"],
    "de_facto": ["actual", "de facto", "in fact"],
    "naturally": ["inherently", "naturally", "instinctively"],
    "willing": ["voluntary", "willing", "ungrudging"],
    "theoretically": ["hypothetically", "theoretically", "conceptually"],
    "practically": ["virtually", "practically", "essentially"],
    "equivalent": ["comparable", "equivalent", "corresponding"],
    "on_time": ["punctual", "on time", "prompt"],
    "industrially": ["factory-related", "industrially", "manufacturing"],
    "sharply": ["abruptly", "sharply", "suddenly"],
    "madly": ["insanely", "madly", "crazily"],
    "meticulously": ["carefully", "meticulously", "thoroughly"],
    "day": ["daytime", "day", "diurnal"],
    "adequately": ["sufficiently", "adequately", "enough"],
    "physically": ["bodily", "physically", "corporeally"],
    "insanely": ["madly", "insanely", "crazily"],
    "civil": ["polite", "civil", "courteous"],
    "certain": ["specific", "certain", "particular"],
    "original": ["authentic", "original", "genuine"],
    "formally": ["officially", "formally", "ceremonially"],
    "initially": ["at first", "initially", "originally"],
    "current": ["present", "current", "contemporary"],
    "overwhelmingly": ["dominantly", "overwhelmingly", "powerfully"],
    "astonishingly": ["amazingly", "astonishingly", "incredibly"],
    "commercially": ["business-related", "commercially", "trade"],
    "joyfully": ["happily", "joyfully", "gleefully"],
    "small": ["little", "small", "tiny"],
    "certainly": ["definitely", "certainly", "undoubtedly"],
    "second_hand": ["used", "second-hand", "pre-owned"],
    "personally": ["individually", "personally", "privately"],
    "evidently": ["clearly", "evidently", "apparently"],
    "up": ["upward", "up", "skyward"],
    "classic": ["traditional", "classic", "timeless"],
    "tastefully": ["stylishly", "tastefully", "elegantly"],
    "south": ["southern", "south", "southerly"],
    "mainly": ["mostly", "mainly", "chiefly"],
    "as_follows": ["namely", "as follows", "specifically"],
    "brisbane_international": ["Brisbane International", "Australian tennis tournament", "Brisbane International"],
    "sufficiently": ["adequately", "sufficiently", "enough"],
    "seem": ["appear", "seem", "look"],
    "surprisingly": ["unexpectedly", "surprisingly", "amazingly"],
    "international": ["global", "international", "worldwide"],
    "interested": ["curious", "interested", "inquisitive"],
    "odd": ["strange", "odd", "peculiar"],
    "chilly": ["cold", "chilly", "cool"],
    "notoriously": ["infamously", "notoriously", "notably"],
    "kind_of": ["sort of", "kind of", "somewhat"],
    "next": ["subsequent", "next", "following"],
    "solely": ["only", "solely", "exclusively"],
    "fallen": ["dropped", "fallen", "descended"],
    "bring": ["deliver", "bring", "carry"],
    "consecutive": ["successive", "consecutive", "sequential"],
    "quickly": ["rapidly", "quickly", "speedily"],
    "and_so_on": ["etcetera", "and so on", "and suchlike"],
    "chemical": ["substance", "chemical", "compound"],
    "intrepidly": ["fearlessly", "intrepidly", "boldly"],
    "legal": ["lawful", "legal", "legitimate"],
    "gaily": ["merrily", "gaily", "cheerfully"],
    "predominantly": ["mostly", "mainly", "predominantly"],
    "happy": ["joyful", "happy", "content"],
    "electronic": ["digital", "electronic", "computerized"],
    "unexpectedly": ["surprisingly", "unexpectedly", "unpredictably"],
    "outdoors": ["outside", "outdoors", "in the open"],
    "asynchronous": ["not simultaneous", "asynchronous", "unsynchronized"],
    "expressly": ["explicitly", "expressly", "clearly"],
    "wise": ["sensible", "wise", "judicious"],
    "manifestly": ["evidently", "manifestly", "clearly"],
    "begin": ["start", "begin", "commence"],
    "militarily": ["in a military manner", "militarily", "by military means"],
    "terribly": ["awfully", "terribly", "dreadfully"],
    "really": ["truly", "really", "genuinely"],
    "high": ["tall", "high", "elevated"],
    "internally": ["inside", "internally", "within"],
    "level_3": ["third level", "level 3", "tertiary"],
    "tight": ["secure", "tight", "firm"],
    "still": ["calm", "still", "quiet"],
    "modern": ["contemporary", "modern", "current"],
    "minimally": ["to a minimal extent", "minimally", "barely"],
    "instinctively": ["innately", "instinctively", "intuitively"],
    "fatal": ["deadly", "fatal", "lethal"],
    "prior": ["before", "prior", "previous"],
    "natural": ["inherent", "natural", "innate"],
    "passive": ["inactive", "passive", "inert"],
    "loudly": ["noisily", "loudly", "vociferously"],
    "collective": ["joint", "collective", "communal"],
    "disproportionately": ["unequally", "disproportionately", "unfairly"],
    "intimately": ["closely", "intimately", "personally"],
    "ill": ["sick", "ill", "unwell"],
    "a_lot": ["much", "a lot", "a great deal"],
    "gravely": ["seriously", "gravely", "solemnly"],
    "violently": ["forcefully", "violently", "aggressively"],
    "especially": ["particularly", "especially", "notably"],
    "kindly": ["nicely", "kindly", "pleasantly"],
    "off": ["away", "off", "distant"],
    "democratically": ["popularly", "democratically", "majority rule"],
    "brutally": ["cruelly", "brutally", "harshly"],
    "experienced": ["seasoned", "experienced", "veteran"],
    "proudly": ["boastfully", "proudly", "haughtily"],
    "completely": ["totally", "completely", "entirely"],
    "conscientiously": ["carefully", "conscientiously", "diligently"],
    "membership": ["enrollment", "membership", "association"],
    "rarely": ["infrequently", "rarely", "seldom"],
    "admirably": ["commendably", "admirably", "laudably"],
    "vinyl": ["vinyl", "polyvinyl", "PVC"],
    "clearly": ["distinctly", "clearly", "obviously"],
    "fast": ["quick", "fast", "speedy"],
    "west": ["western", "west", "westerly"],
    "deeply": ["profoundly", "deeply", "intensely"],
    "worried": ["anxious", "worried", "concerned"],
    "honest": ["truthful", "honest", "sincere"],
    "freeware": ["freeware", "free software", "open source"],
    "flexible": ["adaptable", "flexible", "pliable"],
    "process": ["procedure", "process", "operation"],
    "weighted": ["heavily", "weighted", "loaded"],
    "significant": ["important", "significant", "meaningful"],
    "calmly": ["tranquilly", "calmly", "composedly"],
    "sure": ["certain", "sure", "confident"],
    "at_large": ["at large", "generally", "overall"],
    "friendly": ["amicable", "friendly", "affable"],
    "heavily": ["intensely", "heavily", "strongly"],
    "bound": ["tied", "bound", "restricted"],
    "relatively": ["comparatively", "relatively", "proportionally"],
    "along": ["beside", "along", "next to"],
    "incessantly": ["constantly", "incessantly", "unceasingly"],
    "vigorously": ["energetically", "vigorously", "forcibly"],
    "originally": ["initially", "originally", "at first"],
    "superlatively": ["extremely", "superlatively", "exceedingly"],
    "bashfully": ["shyly", "bashfully", "timidly"],
    "regional": ["local", "regional", "district"],
    "specially": ["specifically", "specially", "especially"],
    "artificial": ["synthetic", "artificial", "man-made"],
    "whole": ["entire", "whole", "complete"],
    "inexhaustibly": ["endlessly", "inexhaustibly", "unceasingly"],
    "sorely": ["deeply", "sorely", "keenly"],
    "de_jure": ["legally", "de jure", "by law"],
    "multiple": ["many", "multiple", "numerous"],
    "willingly": ["voluntarily", "willingly", "readily"],
    "light": ["bright", "light", "illuminated"],
    "ever": ["always", "ever", "forever"],
    "preferably": ["ideally", "preferably", "by choice"],
    "slightly": ["somewhat", "slightly", "a bit"],
    "resolutely": ["determinedly", "resolutely", "firmly"],
    "insecurely": ["unsteadily", "insecurely", "shakily"],
    "intermediate": ["mid-level", "intermediate", "middle"],
    "organized": ["orderly", "organized", "systematic"],
    "eagerly": ["enthusiastically", "eagerly", "keenly"],
    "surely": ["certainly", "surely", "undoubtedly"],
    "universal": ["general", "universal", "common"],
    "particulary": ["particularly", "particulary", "especially"],
    "internationally": ["globally", "internationally", "worldwide"],
    "mandatory": ["required", "mandatory", "obligatory"],
    "deem": ["consider", "deem", "regard"],
    "hopefully": ["optimistically", "hopefully", "with hope"],
    "calamitously": ["disastrously", "calamitously", "catastrophically"],
    "just_now": ["recently", "just now", "lately"],
    "relative": ["comparative", "relative", "proportional"],
    "emotionally": ["mentally", "emotionally", "psychologically"],
    "congressionally": ["legislatively", "congressionally", "by Congress"],
    "tightly": ["securely", "tightly", "firmly"],
    "county": ["region", "county", "district"],
    "all_at_once": ["simultaneously", "all at once", "at the same time"],
    "possibly": ["maybe", "possibly", "perhaps"],
    "deliberately": ["intentionally", "deliberately", "purposefully"],
    "downstream": ["down the river", "downstream", "downcurrent"],
    "consequently": ["therefore", "consequently", "as a result"],
    "even": ["still", "even", "yet"],
    "environmental": ["ecological", "environmental", "green"],
    "uncommonly": ["rarely", "uncommonly", "infrequently"],
    "kinda": ["sort of", "kinda", "kind of"],
    "important": ["significant", "important", "crucial"],
    "educational": ["instructional", "educational", "academic"],
    "subconsciously": ["unconsciously", "subconsciously", "instinctively"],
    "ariane_5": ["Ariane 5", "Ariane 5 rocket", "European Space Agency's Ariane 5"],
    "restricted": ["limited", "restricted", "confined"],
    "successfully": ["effectively", "successfully", "efficiently"],
    "properly": ["correctly", "properly", "appropriately"],
    "synthetic": ["man-made", "synthetic", "artificial"],
    "financially": ["monetarily", "financially", "economically"],
    "super": ["excellent", "super", "outstanding"],
    "liquid": ["fluid", "liquid", "aqueous"],
    "namely": ["specifically", "namely", "to wit"],
    "external": ["outside", "external", "outer"],
    "admittedly": ["granted", "admittedly", "concededly"],
    "solar": ["solar", "solar-powered", "solar-energy"],
    "a_priori": ["deductive", "a priori", "presumptive"],
    "awkwardly": ["ungracefully", "awkwardly", "clumsily"],
    "typically": ["usually", "typically", "normally"],
    "repetitive": ["repetitious", "repetitive", "monotonous"],
    "officially": ["formally", "officially", "legally"],
    "increasingly": ["progressively", "increasingly", "gradually"],
    "stern": ["strict", "stern", "severe"],
    "fucking": ["expletive", "fucking", "cursing"],
    "challenge": ["test", "challenge", "trial"],
    "more": ["additional", "more", "extra"],
    "from_time_to_time": ["occasionally", "from time to time", "periodically"],
    "awake": ["conscious", "awake", "aware"],
    "full": ["complete", "full", "entire"],
    "silent": ["quiet", "silent", "still"],
    "both": ["two", "both", "pair"],
    "unfairly": ["unjustly", "unfairly", "inequitably"],
    "on_average": ["on average", "on the whole", "generally"],
    "maximum": ["greatest", "maximum", "highest"],
    "skillfully": ["expertly", "skillfully", "adeptly"],
    "as": ["like", "as", "similarly"],
    "ago": ["before", "ago", "previously"],
    "at_last": ["finally", "at last", "ultimately"],
    "democratic": ["popular", "democratic", "representative"],
    "all_of_a_sudden": ["suddenly", "all of a sudden", "unexpectedly"],
    "nonstop": ["continuous", "nonstop", "uninterrupted"],
    "cool": ["chilly", "cool", "cold"],
    "actively": ["energetically", "actively", "vigorously"],
    "released": ["unleashed", "released", "liberated"],
    "immeasurably": ["greatly", "immeasurably", "vastly"],
    "close": ["near", "close", "proximate"],
    "lately": ["recently", "lately", "of late"],
    "cellulose": ["cellulose", "fiber", "plant fiber"],
    "thoroughly": ["completely", "thoroughly", "fully"],
    "though": ["although", "though", "nevertheless"],
    "shalt": ["shall", "shalt", "will"],
    "lovingly": ["fondly", "lovingly", "affectionately"],
    "mathematically": ["logically", "mathematically", "arithmetically"],
    "brilliantly": ["brightly", "brilliantly", "vividly"],
    "weakly": ["feeble", "weakly", "frail"],
    "retired": ["inactive", "retired", "former"],
    "ultimately": ["finally", "ultimately", "eventually"],
    "barely": ["scarcely", "barely", "hardly"],
    "unknown": ["unidentified", "unknown", "anonymous"],
    "locally": ["regionally", "locally", "in the area"],
    "integrated": ["combined", "integrated", "unified"],
    "badly": ["poorly", "badly", "inadequately"],
    "outside": ["outdoors", "outside", "outward"],
    "thin": ["slender", "thin", "narrow"],
    "breathtakingly": ["amazingly", "breathtakingly", "astoundingly"],
    "compulsively": ["obsessively", "compulsively", "irresistibly"],
    "roughly": ["approximately", "roughly", "about"],
    "barefoot": ["shoeless", "barefoot", "unshod"],
    "sworn": ["pledged", "sworn", "committed"],
    "genetically": ["biologically", "genetically", "hereditarily"],
    "extremely": ["very", "extremely", "exceedingly"],
    "too": ["also", "too", "likewise"],
    "damned": ["cursed", "damned", "doomed"],
    "social": ["societal", "social", "community"],
    "northern": ["north", "northern", "northerly"],
    "packaging": ["wrapping", "packaging", "container"],
    "fourthly": ["fourth", "fourthly", "in the fourth place"],
    "similar": ["alike", "similar", "like"],
    "recklessly": ["carelessly", "recklessly", "heedlessly"],
    "tired": ["fatigued", "tired", "weary"],
    "extensively": ["broadly", "extensively", "widely"],
    "complement": ["match", "complement", "complete"],
    "personal": ["individual", "personal", "private"],
    "hydroelectric": ["water-generated", "hydroelectric", "hydropower"],
    "unacceptably": ["intolerably", "unacceptably", "unbearably"],
    "immensely": ["greatly", "immensely", "enormously"],
    "triumphantly": ["victoriously", "triumphantly", "successfully"],
    "metal": ["metallic", "metal", "iron"],
    "length": ["distance", "length", "extent"],
    "present": ["existing", "present", "current"],
    "public": ["open", "public", "common"],
    "remote": ["distant", "remote", "far-off"],
    "northeast": ["northeastern", "northeast", "northeasterly"],
    "ahead": ["forward", "ahead", "in advance"],
    "genuinely": ["authentically", "genuinely", "sincerely"],
    "potentially": ["possibly", "potentially", "likely"],
    "agricultural": ["farming", "agricultural", "rural"],
    "compulsory": ["mandatory", "compulsory", "obligatory"],
    "sorry": ["apologetic", "sorry", "regretful"],
    "query": ["question", "query", "inquiry"],
    "humbly": ["modestly", "humbly", "meekly"],
    "densely": ["thickly", "densely", "closely"],
    "distantly": ["remotely", "distantly", "far off"],
    "global": ["worldwide", "global", "universal"],
    "eurocentrist": ["Eurocentrist", "Eurocentric", "Eurocentrism"],
    "lonely": ["solitary", "lonely", "isolated"],
    "importantly": ["significantly", "importantly", "notably"],
    "joyous": ["happy", "joyous", "elated"],
    "mixed": ["blended", "mixed", "varied"],
    "usually": ["normally", "usually", "commonly"],
    "broken": ["damaged", "broken", "shattered"],
    "neatly": ["tidily", "neatly", "orderly"],
    "curious": ["inquisitive", "curious", "interested"],
    "truly": ["genuinely", "truly", "really"],
    "rich": ["wealthy", "rich", "affluent"],
    "procedure": ["process", "procedure", "operation"],
    "delicious": ["tasty", "delicious", "flavorful"],
    "angrily": ["fiercely", "angrily", "wrathfully"],
    "nominally": ["formally", "nominally", "officially"],
    "early": ["premature", "early", "untimely"],
    "magic": ["magical", "magic", "supernatural"],
    "lucky": ["fortunate", "lucky", "blessed"],
    "secondly": ["second", "secondly", "in the second place"],
    "separately": ["individually", "separately", "independently"],
    "for_example": ["for instance", "for example", "as an example"],
    "greatly": ["significantly", "greatly", "largely"],
    "luckily": ["fortunately", "luckily", "happily"],
    "frequent": ["common", "frequent", "regular"],
    "scarcely": ["hardly", "scarcely", "barely"],
    "southwestern": ["southwest", "southwestern", "southerly"],
    "drunk": ["intoxicated", "drunk", "inebriated"],
    "payroll": ["salary list", "payroll", "wage list"],
    "afraid": ["fearful", "afraid", "scared"],
    "all_right": ["okay", "all right", "fine"],
    "wrongly": ["incorrectly", "wrongly", "erroneously"],
    "frozen": ["icy", "frozen", "chilled"],
    "hoechst_roussel_vet": ["Hoechst Roussel Vet", "pharmaceutical company", "Hoechst Roussel Vet"],
    "unless": ["except", "unless", "except if"],
    "publicly": ["openly", "publicly", "in public"],
    "forcibly": ["strongly", "forcibly", "powerfully"],
    "commonly": ["usually", "commonly", "typically"],
    "by_the_way": ["incidentally", "by the way", "in passing"],
    "jointly": ["together", "jointly", "collaboratively"],
    "incumbent": ["current", "incumbent", "existing"],
    "comparatively": ["relatively", "comparatively", "proportionally"],
    "military": ["army", "military", "armed forces"],
    "distinctly": ["clearly", "distinctly", "obviously"],
    "utterly": ["completely", "utterly", "entirely"],
    "perilously": ["dangerously", "perilously", "hazardously"],
    "partly": ["somewhat", "partly", "in part"],
    "structural": ["organized", "structural", "architectural"],
    "arbitrarily": ["randomly", "arbitrarily", "capriciously"],
    "anyway": ["nevertheless", "anyway", "regardless"],
    "specific": ["particular", "specific", "distinctive"],
    "visibly": ["clearly", "visibly", "apparently"],
    "particular": ["specific", "particular", "individual"],
    "out_of_the_blue": ["unexpectedly", "out of the blue", "suddenly"],
    "zealously": ["enthusiastically", "zealously", "eagerly"],
    "comfortably": ["cozily", "comfortably", "snugly"],
    "aleix_espargaró": ["Aleix Espargaró", "Spanish motorcycle racer", "Aleix Espargaró"],
    "gradually": ["slowly", "gradually", "steadily"],
    "xfffe": ["character encoding", "xfffe", "replacement character"]

}


def find_synonyms(word):
    synonyms = []
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.append(lemma.name())
    return synonyms

def is_adverb_in_text(word, text):
    # Generate possible forms of the word
    forms = set()
    forms.add(word.lower())  # Lower-case
    forms.add(word.upper())  # Upper-case
    forms.add(word.capitalize())  # Cap-case

    # Check if any form of the word is present in the text
    for form in forms:
        if form in text.lower():
            return True
    return False

def replace_adverbs(sentence, logical_representation):
    # Tokenize the sentence
    tokens = nltk.word_tokenize(sentence)
    # Extract adverbs from the logical representation
    logical_adverbs = []
    for sense in range(1, 10):  # Iterate from .a.01 to .a.09
        logical_adverbs += [word.split('.')[0] for word in logical_representation.split() if
                                  word.endswith(f'.r.{sense:02d}')]
    #logical_adverbs = [word.split('.')[0] for word in logical_representation.split() if
     #                   word.endswith('.r.01')]  # Assuming .r.01 represents adverbs

    # Replace adverbs
    replaced_sentence = sentence

    for word in logical_adverbs:
        if is_adverb_in_text(word, sentence):
            synonyms = find_synonyms(word)

            if word in manual_synonyms:
             synonyms.extend(manual_synonyms[word])

            if synonyms:
                synonym = random.choice(synonyms)
                # Replace adverbs in both case-sensitive and case-insensitive forms
                replaced_sentence = replaced_sentence.replace(word, synonym)
                replaced_sentence = replaced_sentence.replace(word.capitalize(), synonym.capitalize())
                logical_representation = logical_representation.replace(word, synonym)

    return replaced_sentence, logical_representation

# Read the dataset from "gold_train.sbn"
input_filename = "../italian-english/italian_gold_silver_eng_dataset.txt"
output_filename = "../italian-english/augmentation/english_aug_dataset_files/adv/eng_adverb_aug.sbn"

with open(input_filename, "r") as infile:
    lines = infile.readlines()

# Perform adverb replacement and save the output
replaced_dataset = []

for line in lines:
    sentence, logical_representation = line.strip().split('\t')
    replaced_sentence, replaced_logical_representation = replace_adverbs(sentence,
                                                                         logical_representation)
    replaced_dataset.append((replaced_sentence, replaced_logical_representation))

# Save the output to "adverb_replacement_with_synonyms.sbn"
with open(output_filename, "w") as outfile:
    for sentence, logical_representation in replaced_dataset:
        outfile.write(f"{sentence}\t{logical_representation}\n")
